/**
 * English gallery chrome copy, constrained by `GalleryStrings` to the shape of the Chinese
 * dictionary in strings.ts. Module and catalog titles and descriptions come from the module files
 * and catalog.ts themselves.
 */
import type { GalleryStrings } from "./strings";

export const en: GalleryStrings = {
  brand: {
    title: "Penguin UI",
    subtitle: "Modules",
  },
  rail: {
    theme: "Theme",
    mode: "Mode",
    size: "Size",
    language: "Language",
    langNames: { en: "EN", zh: "中文" },
    modes: { light: "Light", dark: "Dark", system: "System" },
    sizeTitle: (px) => `${px}px root`,
    compare: "Compare themes",
    reducedMotion: "Reduced motion",
    fonts: "Fonts & licences",
    modules: "Modules",
    feedbackTitle: "Feedback",
    feedbackBody:
      "Quote the breadcrumb at a card's bottom left, or copy its address with the link button.",
  },
  intro: {
    title: "Component gallery",
    body: "The shared UI package as fifteen modules, each a realistic composition built from one mock dataset, switchable across three themes, light and dark, three sizes and two languages. Every variant has an address you can quote.",
    resolving: "Resolving tokens…",
    problems: "Module and demo problems",
  },
  section: {
    copyLink: "Copy link",
    copied: "Copied",
    copyBreadcrumb: "Copy breadcrumb",
    parts: "Parts",
    tokens: "Tokens",
    code: "Code",
    variants: "Variants",
    tokensIn: (where, count) => `${count} tokens read, resolved in ${where}`,
    noTokens: "This composition reads no tokens.",
    unset: "unset",
    loadingCode: "Loading source…",
    compareFrame: (theme) => `${theme} preview`,
    partsOf: (count) => `${count} ${count === 1 ? "part" : "parts"}`,
    noParts: "This module lists no parts.",
    replaces: (what) => `replaces ${what}`,
  },
  embed: {
    unknownModule: (id) => `There is no module named “${id}”.`,
    noDemo: (id) => `“${id}” has no demo yet.`,
    nothing: "Name what to render with ?module=<module> or ?demo=<part>.",
  },
  screens: {
    open: "Open full screen",
    back: "Back to the gallery",
    notFound: (name) => `There is no screen named “${name}”.`,
    descriptions: {},
  },
  foundations: {
    surfaces: "Surfaces",
    inks: "Inks",
    lines: "Lines",
    inkWords: ["Text", "Muted", "Subtle"],
    accent: "Accent",
    presetsHint: "The theme's own accent and the five presets a user can pick",
    themeAccent: "theme",
    sampleSend: "Send",
    selectedRow: "Selected",
    sampleLink: "Open the docs",
    linkHover: "hover",
    tones: "Tones",
    toneWords: {
      success: "Running",
      attention: "Waiting",
      danger: "Failed",
      done: "Done",
      neutral: "Idle",
      info: "Syncing",
    },
    charts: "Chart series",
    tokenSeries: "Token mix",
    code: "Code and diff",
    codeLines: {
      before: "const hits = rank(q).slice(0, ",
      removed: "3",
      added: "6",
      after: ");",
      selected: "return cite(hits);",
    },
    typeNote:
      "Each row is set in its own role's tokens; the Chinese column shows how the theme's faces set Chinese with Latin runs in it.",
    scene: {
      pageTier: "page",
      cardTitle: "Docs Expert",
      cardMeta: "3 sessions · $0.0231",
      nested: "Inner radius = outer radius − padding",
      primary: "Save",
      secondary: "Cancel",
      input: "Search sessions",
      badge: "Running",
      menuTier: "z-[60] menu",
      menuItems: ["Pin", "Rename", "Move to…"],
      backdropTier: "z-50 dialog",
      dialogTitle: "Delete this session?",
      dialogBody: "Its transcript and Trace files are deleted with it.",
      cancel: "Cancel",
      confirm: "Delete",
      toastTier: "z-[100] toast",
      toast: "Exported Trace #001",
    },
    radius: "Radius",
    shadows: "Shadow levels",
    spacingPage: {
      title: "Settings",
      appearance: "Appearance",
      theme: "Theme",
      themeOptions: ["Light", "Dark", "System"],
      fontSize: "Font size",
      sizeOptions: ["S", "M", "L"],
      general: "General",
      language: "Language",
      languageOptions: ["中文", "English"],
      notifications: "Notify when done",
    },
    stack0Note: "stack-0: the narrow bars between a glyph and its label",
    controlHeights: "Control heights, measured",
    iconSizes: "Icon sizes",
    iconRegistry: (icons, files) => `${icons} icons from ${files} files`,
    duplicateNames: "One path, several names",
    durations: "Durations × easings",
    reducedNote: "Reduced motion: animations hold their first frame.",
    liveSignal: "Live signals",
    loading: "Loading",
    focusRing: "Focus ring",
    inputFocus: "Input focus",
    selection: "Selection",
    scrollbar: "Scrollbar",
    hookJobs: {
      "ui-glass": "a transient layer over content",
      "ui-eyebrow": "a group label naming the items below it",
      "ui-display": "the one display title of a page or hero",
      "ui-live": "motion for something running right now",
      "ui-frame": "a ruled box with a head, a body, a foot and panes",
      "ui-underline-nav": "the selected-tab marker of a tab bar",
    },
    hookSamples: {
      menu: ["Pin", "Rename", "Delete"],
      group: "Workspaces",
      rows: ["claude-code-expert", "docs-sync", "release-notes"],
      copy: "Copy",
      tabs: ["Overview", "Traces", "Files"],
      streaming: "Writing the answer",
    },
  },
  fonts: {
    title: "Fonts & licences",
    specimens: "Specimens",
    specimensHint: "Each theme's families, one en and one zh paragraph at 16 / 18 / 20 px.",
    declared: "Declared faces",
    declaredHint:
      "The @font-face rules in the page's stylesheets, merged by family, weight and style; a browser downloads a slice only when text uses it.",
    noFaces: "No faces declared.",
    family: "Family",
    weight: "Weight",
    slicesColumn: "Slices",
    loadStatus: "Loaded",
    licences: "Licence texts",
    noLicences: "No licence texts yet.",
    status: { loaded: "loaded", unloaded: "unused", loading: "loading", error: "failed" },
  },
  catalog: {
    modules: {},
    sections: {},
  },
};
