/**
 * English gallery chrome copy, constrained by `GalleryStrings` to the shape of the Chinese
 * dictionary in strings.ts: the surfaces and the library topics are named here, as there.
 */
import type { GalleryStrings } from "./strings";

export const en: GalleryStrings = {
  brand: {
    title: "Penguin UI",
  },
  site: {
    home: "Home",
    surfaces: "Surfaces",
    foundations: "Foundations",
    fonts: "Fonts",
    pages: "Pages",
    search: "Search surfaces",
    searchShortcut: "Ctrl K",
    noMatches: "No surface matches.",
    nav: "Surfaces",
    onThisPage: "On this page",
    settings: "View settings",
    menu: "Open the menu",
    closeMenu: "Close the menu",
    notFound: (id) => `There is no page named “${id}”.`,
    allSurfaces: "All surfaces",
    feedbackTitle: "Feedback",
    feedbackBody:
      "Quote the breadcrumb at the end of a frame's toolbar, or copy the page's address with the link button.",
    feedbackExample: "Frost › Chat · dark",
  },
  surfaceGroups: {
    conversation: "Conversation",
    workbench: "Workbench",
    resources: "Resources",
    measure: "Measure",
    system: "System",
  },
  surfaces: {
    chat: {
      title: "Chat",
      description:
        "A finished Task: thinking, three tool calls, a diff, and a Markdown answer with a table and code.",
      how: "Sidebar › any row of the session list.",
    },
    "chat-running": {
      title: "Chat · tool running",
      description:
        "A Task mid-run: a command is executing, and the tool row shows the running state and its timer.",
      how: "Sidebar › a session row with the running mark.",
    },
    "chat-thinking": {
      title: "Chat · thinking",
      description:
        "A Task mid-run: the model is thinking; the thinking row shows the running state and the text keeps growing.",
      how: "Sidebar › a session row with the running mark.",
    },
    "chat-approval": {
      title: "Chat · awaiting approval",
      description:
        "A Task waiting on a human: a command needs approval; allow or deny it and the Task carries on and ends.",
      how: "Sidebar › a session row with the approval mark.",
    },
    "chat-new": {
      title: "New chat",
      description:
        "The draft page: pick the Agent, Workspace, approval mode and model, then type and send the first message.",
      how: "Sidebar › New chat.",
    },
    agents: {
      title: "Agents",
      description:
        "The Agent list: each Agent's activity curve and its session, tool, Skill and schedule counts.",
      how: "Sidebar › Agents.",
    },
    "agent-settings": {
      title: "Agent settings",
      description:
        "One Agent's settings page: overview, prompt, memory, runtime, tools, Skills, hooks, Vault and schedule tabs.",
      how: "Agents › any Agent.",
    },
    schedules: {
      title: "Schedules",
      description:
        "The Agent settings' schedule tab: periods, next fire time, the bound Session and model.",
      how: "Agents › Agent settings › the Schedules tab.",
    },
    plugins: {
      title: "Plugins",
      description:
        "The plugin library by category, with search and filters; installed Skills and hooks per Agent.",
      how: "Sidebar › Plugins.",
    },
    "plugin-detail": {
      title: "Plugin detail",
      description:
        "One plugin's page: its description, the Skills it brings, its file browser and the install action.",
      how: "Plugins › any plugin.",
    },
    models: {
      title: "Models",
      description:
        "The model table by provider: the default model, credentials, prices, context windows and usage.",
      how: "Sidebar › Models.",
    },
    machines: {
      title: "Machines",
      description:
        "This machine and remote ones: install state, connections, probe results, and adding an ssh host.",
      how: "Sidebar › Machines (admins only).",
    },
    usage: {
      title: "Cost center",
      description:
        "Thirty days of usage: Tokens, cost, requests and success rate, grouped by date, Agent, model or Session, with the error panel.",
      how: "Sidebar › Cost center.",
    },
    benchmark: {
      title: "Evaluation center",
      description:
        "The Benchmark list: published and draft status, case counts, and the score trend across evaluations.",
      how: "Sidebar › Evaluation center.",
    },
    "benchmark-detail": {
      title: "Benchmark detail",
      description:
        "One Benchmark: the score curve, each evaluation's case scores, and the cases' statement and rubric files.",
      how: "Evaluation center › any Benchmark.",
    },
    settings: {
      title: "Settings",
      description:
        "The settings dialog: profile, general, appearance (theme, mode, accent, text size, fonts), account, and the server settings.",
      how: "The account menu at the bottom of the sidebar › Settings.",
    },
    "settings-appearance": {
      title: "Appearance settings",
      description:
        "The settings dialog on its Appearance page: theme, mode, accent, the five text sizes and the font pairing — where theme switching lives.",
      how: "The account menu at the bottom of the sidebar › Settings › Appearance.",
    },
    login: {
      title: "Login",
      description:
        "The sign-in page: the login card over the decorative canvas. Any password signs the demo account in.",
      how: "Any address while signed out.",
    },
  },
  home: {
    eyebrow: "Surface gallery",
    title: "Penguin UI",
    lead: "The real Web App, running in three themes, two modes, five text sizes, the font pairings and two languages — on an in-browser demo API, fully clickable.",
    app: "The app",
    appLead:
      "This is the app itself: the sidebar, every center, the chat and the settings all open. The theme and size controls drive the app in the frame; sending a message streams a scripted reply.",
    index: "Surface index",
    indexLead:
      "One page per surface: the app opened on it, under whatever theme, size and fonts you set.",
    library: "Component library",
    libraryLead:
      "The real Web components, one page per kind, rendered under the theme, mode, size and fonts you set — and interactive.",
    fonts: "Fonts",
    fontsLead: "Each theme's default faces, the current choice, specimens and licences.",
  },
  rail: {
    theme: "Theme",
    themeNames: { github: "Primer", modern: "Frost", geek: "Console" },
    mode: "Mode",
    accent: "Accent",
    accentTheme: "Theme's own",
    size: "Size",
    sizeNames: { xs: "XS", s: "S", m: "M", l: "L", xl: "XL" },
    sizeTitle: (name, px) => `${name} · ${px}px root`,
    fontLatin: "Latin font",
    fontCjk: "CJK font",
    fontTheme: "Theme default",
    fontSystem: "System",
    language: "Language",
    viewport: "Viewport",
    viewports: { desktop: "Desktop", phone: "Phone" },
    langNames: { en: "EN", zh: "中文" },
    modes: { light: "Light", dark: "Dark", system: "System" },
  },
  readout: {
    label: "Fonts in use",
    latin: "Latin",
    cjk: "CJK",
    mono: "Mono",
    system: "System",
    pending: "Reading…",
  },
  crumb: {
    modes: { light: "light", dark: "dark" },
    phone: "phone",
  },
  intro: {
    resolving: "Resolving tokens…",
  },
  frame: {
    open: "Open standalone",
    reload: "Reload",
    frameOf: (theme) => `The app in ${theme}`,
    how: "Where it is in the app",
    route: "Route",
    signedOut: "signed out",
  },
  section: {
    copyLink: "Copy link",
    copyBreadcrumb: "Copy breadcrumb",
    unset: "unset",
  },
  foundations: {
    surfaces: "Surfaces",
    inks: "Inks",
    lines: "Lines",
    inkWords: ["Text", "Muted", "Subtle"],
    accent: "Accent",
    presetsHint:
      "The theme's own accent and the five presets this theme lists; another theme's presets paint nothing here",
    themeAccent: "theme",
    sampleSend: "Send",
    selectedRow: "Selected",
    sampleLink: "Open the docs",
    linkHover: "hover",
    tones: "Tones",
    toneWords: {
      success: "Running",
      attention: "Waiting",
      danger: "Failed",
      done: "Done",
      neutral: "Idle",
      info: "Syncing",
    },
    charts: "Chart series",
    tokenSeries: "Token mix",
    code: "Code and diff",
    codeLines: {
      before: "const hits = rank(q).slice(0, ",
      removed: "3",
      added: "6",
      after: ");",
      selected: "return cite(hits);",
    },
    typeNote:
      "Each row is set in its own role's tokens; the Chinese column shows how the theme's faces set Chinese with Latin runs in it.",
    scene: {
      pageTier: "page",
      cardTitle: "Docs Expert",
      cardMeta: "3 sessions · $0.0231",
      nested: "Inner radius = outer radius − padding",
      primary: "Save",
      secondary: "Cancel",
      input: "Search sessions",
      badge: "Running",
      menuTier: "z-[60] menu",
      menuItems: ["Pin", "Rename", "Move to…"],
      backdropTier: "z-50 dialog",
      dialogTitle: "Delete this session?",
      dialogBody: "Its transcript and Trace files are deleted with it.",
      cancel: "Cancel",
      confirm: "Delete",
      toastTier: "z-[100] toast",
      toast: "Exported Trace #001",
    },
    radius: "Radius",
    shadows: "Shadow levels",
    spacingPage: {
      title: "Settings",
      appearance: "Appearance",
      theme: "Theme",
      themeOptions: ["Light", "Dark", "System"],
      fontSize: "Text size",
      sizeOptions: ["XS", "S", "M", "L", "XL"],
      general: "General",
      language: "Language",
      languageOptions: ["中文", "English"],
      notifications: "Notify when done",
    },
    stack0Note: "stack-0: the narrow bars between a glyph and its label",
    controlHeights: "Control heights, measured",
    iconSizes: "Icon sizes",
    iconRegistry: (icons, files) => `${icons} icons from ${files} files`,
    duplicateNames: "One path, several names",
    durations: "Durations × easings",
    reducedNote: "Reduced motion: every change shows its end state at once.",
    liveSignal: "Live signals",
    loading: "Loading",
    focusRing: "Focus ring",
    inputFocus: "Input focus",
    selection: "Selection",
    scrollbar: "Scrollbar",
    spaceUnit: "Space unit",
    spaceUnitNote: "Every spacing and size utility is a multiple of it: h-8 is eight units.",
    shell: "Shell",
    shellNote:
      "The app window through .ui-shell: the field, the navigation column and the main column, related as each theme decides.",
    presence: "Presence",
    presenceNote:
      "A menu from the top, a dialog from the centre, a toast from the bottom — each on the active theme's enter and exit tokens.",
    reveal: "Reveal",
    revealNote:
      "Streamed text arrives chunk by chunk; each chunk moves once, on the reveal tokens, as it appears.",
    layout: "Layout",
    layoutNote: "The sidebar's width between expanded and rail, on the layout tokens.",
    replay: "Replay",
    replayAll: "Replay all",
    motionSpecimens: {
      menu: "Menu",
      dialog: "Dialog",
      toast: "Toast",
      trigger: "More",
      sidebarRows: ["New chat", "Agents", "Models"],
    },
    hookJobs: {
      "ui-glass": "a transient layer over content",
      "ui-eyebrow": "a group label naming the items below it",
      "ui-display": "the one display title of a page or hero",
      "ui-live": "motion for something running right now",
      "ui-frame": "a ruled box with a head, a body, a foot and panes",
      "ui-underline-nav": "the selected-tab marker of a tab bar",
      "ui-shell": "the app window: a navigation column beside a main column",
      "ui-icon-decor": "an icon its label already says: a theme may tint it or drop it",
      "ui-tree":
        "a list whose rows nest: a file tree, a work group's tool rows, the subagent graph",
      "ui-field": "a labelled control row: a form field or a settings row",
      "ui-activity": "a thinking or tool row at work: running, done or in error",
      "ui-notice":
        "a notice strip or toast, coloured by its tone: info, success, warning, danger or neutral",
      "ui-chart": "a chart: its grid, axes, lines, areas, bars and points",
    },
    hookSamples: {
      menu: ["Pin", "Rename", "Delete"],
      group: "Workspaces",
      rows: ["claude-code-expert", "docs-sync", "release-notes"],
      copy: "Copy",
      tabs: ["Overview", "Traces", "Files"],
      streaming: "Writing the answer",
      tree: {
        root: "claude-code-expert",
        dir: "src",
        files: ["rag.ts", "embed.ts"],
        last: "README.md",
      },
      field: {
        name: "Name",
        value: "Docs Expert",
        hint: "Shown in the sidebar and in messages.",
        notify: "Notify when done",
        notifyHint: "A system notification when a Task ends.",
      },
    },
  },
  fonts: {
    title: "Fonts",
    pages: { defaults: "Defaults", specimens: "Specimens", licences: "Licences" },
    defaultsTitle: "Default faces",
    defaultsHint:
      "Each theme's default face per role: Latin (reading and interface), CJK and mono. “System” leaves the role to the platform.",
    system: "System",
    current: "Current choice",
    currentHint:
      "The pairing picked in the top bar; “theme default” is the active theme's row above. What actually renders is on the next line.",
    followsTheme: (theme) => `Theme default (${theme})`,
    specimensTitle: "Specimens",
    licencesTitle: "Licences",
    specimens: "Specimens",
    specimensHint:
      "Each theme's families, one en and one zh paragraph at the five text sizes (14 / 15 / 16 / 18 / 20 px).",
    declared: "Declared faces",
    declaredHint:
      "The @font-face rules in the page's stylesheets, merged by family, weight and style; a browser downloads a slice only when text uses it.",
    noFaces: "No faces declared.",
    family: "Family",
    weight: "Weight",
    slicesColumn: "Slices",
    loadStatus: "Loaded",
    licences: "Licence texts",
    noLicences: "No licence texts yet.",
    status: { loaded: "loaded", unloaded: "unused", loading: "loading", error: "failed" },
  },
  library: {
    title: "Component library",
    groups: { components: "Components", foundations: "Foundations" },
    topics: {
      buttons: {
        title: "Buttons",
        description: "Four variants, two sizes and the icon button; disabled and busy.",
      },
      inputs: {
        title: "Inputs and forms",
        description:
          "Input, textarea, password and the field scaffolding: label, hint, info and error.",
      },
      pickers: {
        title: "Pickers",
        description: "Select, segmented control, switch, option menu and dropdown.",
      },
      toasts: {
        title: "Toasts",
        description:
          "The notice after an action completes: success, info, attention and error, fired from buttons.",
      },
      notices: {
        title: "Notice strips",
        description: "A notice that owns a row: every tone, with and without actions.",
      },
      dialogs: {
        title: "Dialogs",
        description: "Modal, confirmation, drawer and bottom sheet.",
      },
      tooltips: {
        title: "Tooltips",
        description:
          "Hints on hover and focus: the data-tooltip attribute and the Tooltip component.",
      },
      tabs: { title: "Tabs", description: "The underline tab switcher, with an update badge." },
      badges: {
        title: "Badges and status",
        description: "Badges, run-state icons, session activity marks and the update dot.",
      },
      empty: {
        title: "Empty states",
        description: "The placeholder for a list or detail with nothing in it, with an action.",
      },
      loading: { title: "Loading", description: "The spinner and the skeletons." },
      charts: {
        title: "Charts",
        description:
          "The chart foundation: the primitives every chart draws through, the current theme's chart tokens, and every chart built on them — the donut, cost trend and token bars, requests and success rate, the activity and score sparklines, the Trace timeline.",
      },
      avatars: { title: "Avatars", description: "The user and agent avatars at their sizes." },
      files: { title: "Files", description: "The file tree and the read-only file browser." },
      colour: {
        title: "Colour",
        description: "Surfaces, inks, lines, the accent, the tones, chart series and code colours.",
      },
      type: { title: "Typography", description: "Size, line height and weight per role." },
      shape: { title: "Shape", description: "Radii, the shadow tiers and nesting." },
      density: { title: "Density", description: "The space unit and the control heights." },
      focus: { title: "Focus", description: "Focus ring, input focus, selection and scrollbars." },
      motion: { title: "Motion", description: "Presence, reveal, layout, durations and easing." },
      icons: { title: "Icons", description: "Icon sizes and the Web App's icon registry." },
      hooks: {
        title: "Hooks",
        description: "The structural hooks a theme may redraw, one by one.",
      },
    },
    buttons: {
      variants: "Variants",
      primary: "Save",
      secondary: "Cancel",
      danger: "Delete",
      ghost: "More",
      sizes: "Sizes",
      md: "Default size",
      sm: "Small",
      icon: "Icon button",
      states: "States",
      disabled: "Disabled",
      busy: "Saving…",
    },
    inputs: {
      basics: "Inputs",
      name: "Name",
      namePlaceholder: "Docs Expert",
      nameHint: "Shown in the sidebar and in messages.",
      email: "Email",
      emailValue: "zheng@example",
      emailError: "The address is incomplete.",
      required: "Required",
      info: "With info",
      infoText: "Takes effect when the next Task starts.",
      sizes: "Sizes",
      base: "Base size",
      small: "Form size",
      textarea: "Textarea",
      textareaPlaceholder: "Write a system prompt…",
      mono: "Monospace",
      monoValue: "temperature: 0.2\nmax_tokens: 4096",
      password: "Password",
      passwordHint: "At least 12 characters.",
    },
    pickers: {
      select: "Select",
      selectLabel: "Model",
      options: ["DeepSeek V4.1 Flash", "Claude Sonnet 4.5", "GLM-5.3"],
      segmented: "Segmented",
      segments: ["Light", "Dark", "System"],
      switches: "Switch",
      switchLabel: "Notify when done",
      switchHint: "A system notification when a Task ends.",
      switchOff: "Short tool names",
      optionMenu: "Option menu",
      optionLabel: "Permission",
      choices: [
        {
          value: "r",
          trigger: "r",
          label: "Read only",
          description: "Can only read the workspace.",
        },
        {
          value: "rw",
          trigger: "rw",
          label: "Read and write",
          description: "May change files in the workspace.",
        },
        {
          value: "ask",
          trigger: "ask",
          label: "Ask each time",
          description: "Asks before every write.",
        },
      ],
      dropdown: "Dropdown",
      menu: "More actions",
      menuItems: ["Pin", "Rename", "Move to…", "Delete"],
    },
    toasts: {
      fire: "Fire a toast",
      hint: "A toast appears at the top of the page and leaves after a few seconds; an error or an advisory stays longer.",
      success: "Success",
      info: "Info",
      attention: "Attention",
      error: "Error",
      successText: "Saved.",
      infoText: "The index is rebuilding in the background.",
      attentionText: "Saved, but 2 fields were truncated.",
      errorText: "Connection failed: api.example is unreachable.",
    },
    notices: {
      plain: "Every tone",
      dotted: "With a leading mark",
      withActions: "With actions",
      texts: {
        link: "Version 0.3.0 is available.",
        success: "Index rebuilt: 214 files.",
        busy: "Syncing the corpus…",
        attention: "1 unexpected error.",
        danger: "The model returned 401: invalid key.",
        muted: "This session is archived.",
      },
      action: "View",
      dismiss: "Dismiss",
    },
    dialogs: {
      modal: "Modal",
      openModal: "Open a dialog",
      modalTitle: "Rename session",
      modalBody: "The new name shows in the sidebar and in messages.",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirmation",
      openConfirm: "Delete session…",
      confirmTitle: "Delete this session?",
      confirmBody: "The transcript and the Trace files go with it; this cannot be undone.",
      confirmLabel: "Delete",
      drawer: "Drawer",
      openDrawer: "Open a drawer",
      drawerTitle: "Navigation",
      drawerBody: "The sidebar at phone width slides in from the edge.",
      sheet: "Bottom sheet",
      openSheet: "Open a sheet",
      sheetTitle: "Files",
      sheetBody: "Drag up for the full screen, down to close.",
    },
    tooltips: {
      attribute: "The data-tooltip attribute",
      attributeHint:
        "Any element takes the attribute; an icon-only button carries an aria-label too.",
      component: "The Tooltip component",
      componentHint: "For a trigger that needs the wrapper: beside it, or below it.",
      truncated: "Truncated text",
      truncatedHint: "A command or title the row cannot fit goes whole into the hint.",
      edit: "Edit",
      copy: "Copy",
      settings: "Settings",
      beside: "Beside",
      below: "Below",
      command:
        "pnpm --filter @prismshadow/penguin-web exec vitest run test/session-activity.test.ts --reporter verbose",
    },
    tabs: {
      basic: "Tab switcher",
      badged: "With an update badge",
      items: ["Overview", "Trace", "Files", "Settings"],
      badgeText: "3 skills can be updated",
      body: (tab) => `The “${tab}” tab's content.`,
    },
    badges: {
      badges: "Badges",
      tones: {
        gray: "default",
        brand: "origin",
        green: "running",
        yellow: "free",
        amber: "aborted",
        red: "failed",
      },
      status: "Run state",
      states: {
        running: "Running",
        waiting: "Waiting for approval",
        done: "Done",
        failed: "Failed",
        stopped: "Stopped",
      },
      activity: "Session activity",
      activities: { running: "Running", compacting: "Compacting", completedUnread: "Unread reply" },
      marks: "Other marks",
      background: "Background tasks",
      schedule: "Scheduled",
      dot: "Update dot",
      dotAnchor: "Plugins",
      pill: "Update pill",
      pillText: "3 updates",
    },
    empty: {
      page: "Page empty state",
      title: "No sessions yet",
      description: "Sessions appear here once you send a first message.",
      action: "New chat",
      settings: "Settings empty state",
      settingsText: "No MCP servers added yet.",
    },
    loading: {
      spinner: "Spinner",
      sizes: "Three sizes",
      skeleton: "Skeletons",
      list: "List",
      card: "Card",
    },
    charts: {
      parts: {
        primitives: "Primitives",
        primitivesHint:
          "Every chart draws its marks through these alone: they read the theme's chart tokens and write data-part, the one place a token becomes SVG or HTML.",
        tokens: "The current theme's chart tokens",
        tokensHint:
          "Read from this frame root's computed style; read again after a theme, mode or accent change.",
        charts: "Charts built on them",
        chartsHint: "Every chart kind in the app, on demo data.",
      },
      primitives: {
        bar: "ChartBar",
        barHint: "Its width from bar-fill; top radius, outline and fill opacity each from a token.",
        line: "ChartLine",
        lineHint: "One set of points drawn once per curve; the stroke width from a token.",
        curves: { linear: "linear", smooth: "smooth", step: "step" },
        area: "ChartArea",
        areaHint: "The fill under a line, its opacity from a token.",
        point: "ChartPoint",
        pointHint: "Radius from a token; the theme decides round or square.",
        arc: "ChartArc",
        arcHint:
          "One arc of a ring: the track is a grid part, each segment a Token kind or a slot.",
        grid: "ChartGrid and ChartAxis",
        gridHint: "Grid and axis inks from tokens; the theme decides solid or dashed.",
        timeline: "TimelineBar",
        timelineHint: "The Trace timeline's HTML bar, each of the five kinds on its slot.",
        kinds: {
          thinking: "thinking",
          text: "reply",
          tool_call: "tool call",
          approval: "approval wait",
          tool: "tool run",
        },
      },
      palette: "Palette",
      geometry: "Geometry",
      tokenMeaning: {
        "--ui-chart-1": "slot 1 · violet",
        "--ui-chart-2": "slot 2 · amber",
        "--ui-chart-3": "slot 3 · sky",
        "--ui-chart-4": "slot 4 · rose",
        "--ui-chart-5": "slot 5 · emerald",
        "--ui-chart-6": "slot 6 · fuchsia",
        "--ui-chart-7": "slot 7 · spare",
        "--ui-chart-8": "slot 8 · spare",
        "--ui-chart-ref": "reference line",
        "--ui-chart-cache-read": "cache read",
        "--ui-chart-cache-write": "cache write",
        "--ui-chart-output": "output",
        "--ui-chart-grid": "grid",
        "--ui-chart-axis": "axis",
        "--ui-chart-bar-fill": "share of its band a bar fills (0–1)",
        "--ui-chart-bar-radius": "bar top radius",
        "--ui-chart-bar-stroke": "bar outline width",
        "--ui-chart-bar-stroke-color": "bar outline colour (series = the series colour)",
        "--ui-chart-bar-opacity": "bar fill opacity (0–1)",
        "--ui-chart-line-width": "line width",
        "--ui-chart-point-radius": "data point radius",
        "--ui-chart-curve": "curve (linear / smooth / step)",
        "--ui-chart-area-opacity": "area fill opacity (0–1)",
      },
      donut: "Token donut",
      donutHint:
        "Cache reads, cache writes and output; the ring's remainder warns as usage nears the limit.",
      trend: "Cost trend",
      trendHint: "Fourteen days of cost as a line; hover a day.",
      tokens: "Token usage",
      tokensHint:
        "Daily tokens stacked by kind, with the cache-hit-rate curve over them; hover a legend entry to highlight one.",
      requests: "Requests and success rate",
      requestsHint: "Daily requests stacked by agent, each with its success-rate line.",
      agents: ["docs-expert", "release-notes"],
      activity: "Activity sparkline",
      activityHint:
        "The agent card's fourteen-day session count curve; relative ups and downs only.",
      sparkline: "Score sparkline",
      sparklineHint: "One benchmark's scores over its runs, the newest marked.",
      timeline: "Trace timeline",
      timelineHint:
        "One Task's model segments and tool calls: thinking, reply, tool-call generation, approval wait and execution, each in its lane.",
    },
    avatars: {
      user: "User avatar",
      agent: "Agent avatar",
      userNames: ["admin", "Demo admin"],
      agents: [
        { id: "docs-expert", name: "Docs Expert" },
        { id: "release-notes", name: "Release Notes" },
        { id: "qa", name: "QA" },
      ],
    },
    files: {
      tree: "File tree",
      treeLabel: "Workspace",
      browser: "File browser",
      header: "docs-expert",
      emptyPreview: "Pick a file on the left to preview it.",
      emptyDir: "Empty directory",
      readme:
        "# Docs Expert\n\nBuilds a BM25 index over `corpus/` and answers questions about the Claude Code docs.\n\n- `src/rag.ts` — retrieval\n- `test/` — cases",
    },
  },
};
