/**
 * Gallery chrome copy (bilingual): this file holds the Chinese dictionary `zh` and the
 * `GalleryStrings` shape; the English dictionary lives in strings-en.ts. These strings are the
 * gallery's own and never reach the product. Theme display names are per language (通用 / 白领 /
 * 极客 here, Primer / Frost / Console in English) and so are breadcrumbs; theme ids, token names,
 * accent preset ids and font names stay English in both.
 *
 * `surfaces` names the app's surfaces the gallery frames (src/app/surfaces.ts) and `library`
 * the component library's topics (src/library/topics.ts), in both dictionaries; a test checks
 * each covers every id.
 */
import type { HookName, ThemeId, ToneName } from "@prismshadow/penguin-ui";
import type { TextSize } from "@prismshadow/penguin-ui/boot";
import type { SurfaceGroupId, SurfaceId } from "./app/surfaces";
import type { ChartToken } from "./library/chart-tokens";
import type { TopicGroupId, TopicId } from "./library/topics";

/** What a surface page says: its title, one line on what the frame shows, and how the app reaches it. */
export interface SurfaceCopy {
  title: string;
  description: string;
  /** Where the surface sits in the app, for a reader who wants to find it themselves. */
  how: string;
}

export const zh = {
  brand: {
    title: "Penguin UI",
  },
  /** The top bar's page links, the left nav, the "on this page" list and the phone drawer. */
  site: {
    home: "首页",
    surfaces: "界面",
    foundations: "基础",
    fonts: "字体",
    pages: "页面",
    search: "搜索界面",
    searchShortcut: "Ctrl K",
    noMatches: "没有匹配的界面。",
    nav: "界面列表",
    onThisPage: "本页目录",
    settings: "显示设置",
    menu: "打开菜单",
    closeMenu: "关闭菜单",
    notFound: (id: string) => `没有名为「${id}」的页面。`,
    allSurfaces: "全部界面",
    feedbackTitle: "反馈",
    feedbackBody: "引用预览工具条末尾的路径，或用链接按钮复制这一页的地址。",
    feedbackExample: "白领 › 对话 · 深色",
  },
  /** The surface groups (src/app/surfaces.ts): the index's headings, the nav's eyebrows, a page's eyebrow. */
  surfaceGroups: {
    conversation: "对话",
    workbench: "工作台",
    resources: "资源",
    measure: "度量",
    system: "系统",
  } as Record<SurfaceGroupId, string>,
  surfaces: {
    chat: {
      title: "对话",
      description:
        "一次完成的任务：思考、三次工具调用、一处差异、一段带表格与代码的 Markdown 回答。",
      how: "侧栏 › 会话列表中的任意一行。",
    },
    "chat-running": {
      title: "对话 · 工具运行中",
      description: "任务进行中：一条命令正在执行，工具行显示运行状态与计时。",
      how: "侧栏 › 带运行标记的会话行。",
    },
    "chat-thinking": {
      title: "对话 · 思考中",
      description: "任务进行中：模型正在思考，思考行显示运行状态，文字仍在增长。",
      how: "侧栏 › 带运行标记的会话行。",
    },
    "chat-approval": {
      title: "对话 · 待审批",
      description: "任务等待人工：一条命令需要批准，允许或拒绝之后任务继续并结束。",
      how: "侧栏 › 带审批标记的会话行。",
    },
    "chat-new": {
      title: "新对话",
      description: "草稿页：选择智能体、工作区、审批模式与模型，输入并发送第一条消息。",
      how: "侧栏 › 新对话。",
    },
    agents: {
      title: "智能体",
      description: "智能体列表：每个智能体的活动曲线、会话数、工具、Skill 与定时任务计数。",
      how: "侧栏 › 智能体。",
    },
    "agent-settings": {
      title: "智能体设置",
      description:
        "一个智能体的设置页：概览、提示词、记忆、运行时、工具、Skill、钩子、Vault 与定时任务标签页。",
      how: "智能体 › 任意一个智能体。",
    },
    schedules: {
      title: "定时任务",
      description: "智能体设置的定时任务标签页：周期、下次触发、绑定的会话与模型。",
      how: "智能体 › 智能体设置 › 定时任务标签页。",
    },
    plugins: {
      title: "插件市场",
      description: "插件库按分类列出，带搜索与筛选；已安装的 Skill 与钩子按智能体显示。",
      how: "侧栏 › 插件市场。",
    },
    "plugin-detail": {
      title: "插件详情",
      description: "一个插件的详情页：说明、它带来的 Skill、文件浏览器与安装入口。",
      how: "插件市场 › 任意一个插件。",
    },
    models: {
      title: "模型库",
      description: "按供应商分组的模型表：默认模型、凭据、价格、上下文窗口与用量。",
      how: "侧栏 › 模型库。",
    },
    machines: {
      title: "机器",
      description: "本机与远程机器：安装状态、连接、探测结果，以及添加 ssh 主机。",
      how: "侧栏 › 机器（仅管理员）。",
    },
    usage: {
      title: "成本中心",
      description:
        "三十天的用量：Token、花费、请求数与成功率，按日期、智能体、模型或会话分组，附错误面板。",
      how: "侧栏 › 成本中心。",
    },
    benchmark: {
      title: "评估中心",
      description: "评估任务列表：已发布与草稿状态、用例数、历次评估的分数走势。",
      how: "侧栏 › 评估中心。",
    },
    "benchmark-detail": {
      title: "评估详情",
      description: "一个评估任务：分数曲线、每轮评估的用例得分、用例的题面与评分标准文件。",
      how: "评估中心 › 任意一个评估任务。",
    },
    settings: {
      title: "设置",
      description:
        "设置对话框：个人资料、通用、外观（主题、明暗、强调色、字号、字体）、账户，以及服务器设置。",
      how: "侧栏底部的账户菜单 › 设置。",
    },
    "settings-appearance": {
      title: "外观设置",
      description:
        "设置对话框停在「外观」页：主题、明暗、强调色、五档字号与字体组合——主题切换就在这里。",
      how: "侧栏底部的账户菜单 › 设置 › 外观。",
    },
    login: {
      title: "登录",
      description: "登录页：装饰画布上的登录卡片。任意密码即可登录演示账户。",
      how: "未登录时的任意地址。",
    },
  } as Record<SurfaceId, SurfaceCopy>,
  home: {
    eyebrow: "界面画廊",
    title: "Penguin UI",
    lead: "真实的 Web App，在三套主题、两种明暗、五档字号、可选字体组合与两种语言下运行——数据来自浏览器内的演示接口，可以随意点击。",
    app: "应用",
    appLead:
      "这就是应用本身：侧栏、各个中心、对话与设置都能点开。主题与字号等控件作用于框内的应用；发送消息会得到一段脚本回复。",
    index: "界面索引",
    indexLead: "每个界面一页：应用停在该界面上，切换主题、字号与字体即可查看。",
    library: "组件库",
    libraryLead: "真实的 Web 组件，按类别各一页，在当前主题、明暗、字号与字体下渲染，可以操作。",
    fonts: "字体",
    fontsLead: "每个主题的默认字体、当前选择、字样与许可。",
  },
  /**
   * The view controls' copy, in the top bar; the key keeps the name of the rail that held them,
   * which the Foundations boards read (`S.rail.langNames`).
   */
  rail: {
    theme: "主题",
    themeNames: { github: "通用", modern: "白领", geek: "极客" } as Record<ThemeId, string>,
    mode: "明暗",
    accent: "强调色",
    accentTheme: "随主题",
    size: "字号",
    sizeNames: { xs: "特小", s: "小", m: "中", l: "大", xl: "特大" } as Record<TextSize, string>,
    sizeTitle: (name: string, px: number) => `${name} · 根字号 ${px}px`,
    fontLatin: "英文字体",
    fontCjk: "中文字体",
    fontTheme: "随主题",
    fontSystem: "系统",
    language: "语言",
    viewport: "视口",
    viewports: { desktop: "桌面", phone: "手机" },
    langNames: { en: "EN", zh: "中文" },
    modes: { light: "浅色", dark: "深色", system: "跟随系统" },
  },
  /** The current fonts, read from the framed app: the role labels before each family. */
  readout: {
    label: "当前字体",
    latin: "英文",
    cjk: "中文",
    mono: "等宽",
    system: "系统",
    pending: "读取中…",
  },
  /** The breadcrumb's own words; everything else in it is a name from elsewhere. */
  crumb: {
    modes: { light: "浅色", dark: "深色" },
    phone: "手机",
  },
  intro: {
    resolving: "正在解析令牌…",
  },
  /** A framed app's toolbar and captions. */
  frame: {
    open: "单独打开",
    reload: "重新载入",
    frameOf: (theme: string) => `${theme} 下的应用`,
    how: "在应用里的位置",
    route: "路由",
    signedOut: "未登录",
  },
  section: {
    copyLink: "复制链接",
    copyBreadcrumb: "复制路径",
    unset: "未定义",
  },
  foundations: {
    surfaces: "表面",
    inks: "文字",
    lines: "线条",
    inkWords: ["正文", "次要", "弱化"] as readonly string[],
    accent: "强调色",
    presetsHint: "主题自带的强调色，与当前主题列出的五个预设；别的主题的预设在这里不生效",
    themeAccent: "主题",
    sampleSend: "发送",
    selectedRow: "选中",
    sampleLink: "打开文档",
    linkHover: "悬停",
    tones: "语义色调",
    toneWords: {
      success: "运行中",
      attention: "等待中",
      danger: "失败",
      done: "已完成",
      neutral: "空闲",
      info: "同步中",
    } as Record<ToneName, string>,
    charts: "图表序列",
    tokenSeries: "Token 构成",
    code: "代码与差异",
    codeLines: {
      before: "const hits = rank(q).slice(0, ",
      removed: "3",
      added: "6",
      after: ");",
      selected: "return cite(hits);",
    },
    typeNote: "每一行都用各自角色的令牌排版；中文列显示主题字体如何排中文与夹在其中的拉丁文字。",
    scene: {
      pageTier: "页面",
      cardTitle: "Docs Expert",
      cardMeta: "3 个会话 · $0.0231",
      nested: "内层方框的圆角 = 外层圆角 − 内边距",
      primary: "保存",
      secondary: "取消",
      input: "搜索会话",
      badge: "运行中",
      menuTier: "z-[60] 菜单",
      menuItems: ["置顶", "重命名", "移动到…"] as readonly string[],
      backdropTier: "z-50 对话框",
      dialogTitle: "删除这个会话？",
      dialogBody: "对话记录与 Trace 文件会一并删除。",
      cancel: "取消",
      confirm: "删除",
      toastTier: "z-[100] 通知",
      toast: "已导出 Trace #001",
    },
    radius: "圆角",
    shadows: "阴影层级",
    spacingPage: {
      title: "设置",
      appearance: "外观",
      theme: "主题",
      themeOptions: ["浅色", "深色", "跟随系统"] as readonly string[],
      fontSize: "字号",
      sizeOptions: ["特小", "小", "中", "大", "特大"] as readonly string[],
      general: "通用",
      language: "语言",
      languageOptions: ["中文", "English"] as readonly string[],
      notifications: "完成时通知",
    },
    stack0Note: "stack-0：图标与文字之间的窄条",
    controlHeights: "控件高度（实测）",
    iconSizes: "图标尺寸",
    iconRegistry: (icons: number, files: number) => `${icons} 个图标，来自 ${files} 个文件`,
    duplicateNames: "同一路径的多个名字",
    durations: "时长 × 缓动",
    reducedNote: "已减弱动效：每个变化直接呈现终态。",
    liveSignal: "实时信号",
    loading: "加载中",
    focusRing: "焦点环",
    inputFocus: "输入框焦点",
    selection: "选区",
    scrollbar: "滚动条",
    spaceUnit: "间距单位",
    spaceUnitNote: "所有间距与尺寸工具类都是它的倍数：h-8 即八个单位。",
    shell: "外壳",
    shellNote: "经 .ui-shell 的应用窗口：底场、导航列与主列，各主题自行决定它们的关系。",
    presence: "进出",
    presenceNote: "菜单自上方、对话框自中心、通知自下方进出，各按当前主题的进出令牌。",
    reveal: "显现",
    revealNote: "流式文本逐块显现，每一块只在出现时按显现令牌动一次。",
    layout: "布局",
    layoutNote: "侧栏在展开与图标栏之间的宽度变化，按布局令牌。",
    replay: "重放",
    replayAll: "全部重放",
    motionSpecimens: {
      menu: "菜单",
      dialog: "对话框",
      toast: "通知",
      trigger: "更多",
      sidebarRows: ["新对话", "智能体", "模型库"] as readonly string[],
    },
    hookJobs: {
      "ui-glass": "盖在内容之上的临时层",
      "ui-eyebrow": "为下方一组条目命名的分组标签",
      "ui-display": "页面或主视觉唯一的展示标题",
      "ui-live": "正在进行之物的动效",
      "ui-frame": "带头部、主体、底部与窗格的细线框",
      "ui-underline-nav": "标签栏中选中项的标记",
      "ui-shell": "应用窗口：导航列与主列",
      "ui-icon-decor": "标签已经说明了的图标：主题可以着色或不画",
      "ui-tree": "行会嵌套的列表：文件树、工作组的工具行、子 Agent 调用图",
      "ui-field": "带标签的控件行：表单字段或设置行",
      "ui-activity": "正在工作的思考行或工具行：运行中、已完成或出错",
      "ui-notice": "提示条与弹出通知：按语气（信息、成功、警告、错误、中性）着色",
      "ui-chart": "统计图：网格、坐标轴、折线、面积、柱与数据点",
      "ui-scrim": "对话框、抽屉与面板背后的遮罩层",
    } as Record<HookName, string>,
    hookSamples: {
      menu: ["置顶", "重命名", "删除"] as readonly string[],
      group: "工作区",
      rows: ["claude-code-expert", "docs-sync", "release-notes"] as readonly string[],
      copy: "复制",
      tabs: ["概览", "轨迹", "文件"] as readonly string[],
      streaming: "正在写回答",
      tree: {
        root: "claude-code-expert",
        dir: "src",
        files: ["rag.ts", "embed.ts"] as readonly string[],
        last: "README.md",
      },
      field: {
        name: "名称",
        value: "Docs Expert",
        hint: "在侧栏与消息中显示的名字。",
        notify: "完成时通知",
        notifyHint: "Task 结束时弹出系统通知。",
      },
    },
  },
  fonts: {
    title: "字体",
    pages: { defaults: "默认字体", specimens: "字样", licences: "许可" },
    defaultsTitle: "默认字体",
    defaultsHint:
      "每个主题各角色的默认字体：英文（正文与界面）、中文与等宽。「系统字体」指交给平台决定。",
    system: "系统字体",
    current: "当前选择",
    currentHint: "顶栏里选定的字体组合；「随主题」即上表中当前主题的一行。实际渲染的字体见下一行。",
    followsTheme: (theme: string) => `随主题（${theme}）`,
    specimensTitle: "字样",
    licencesTitle: "许可",
    specimens: "字样",
    specimensHint: "每个主题的字体族，在五档字号（14 / 15 / 16 / 18 / 20 px）下各排一段中英文。",
    declared: "已声明的字体",
    declaredHint:
      "页面样式表中的 @font-face，按字体族、字重与样式合并；只有文本用到某个分片时浏览器才会下载它。",
    noFaces: "尚未声明任何字体。",
    family: "字体族",
    weight: "字重",
    slicesColumn: "分片",
    loadStatus: "加载情况",
    licences: "许可文本",
    noLicences: "还没有许可文本。",
    status: { loaded: "已加载", unloaded: "未使用", loading: "加载中", error: "失败" },
  },
  /** The component library: its topics, and the words each board prints. */
  library: {
    title: "组件库",
    groups: { components: "组件", foundations: "视觉基础" } as Record<TopicGroupId, string>,
    topics: {
      buttons: { title: "按钮", description: "四种变体、两档尺寸与图标按钮，以及禁用与进行中。" },
      inputs: {
        title: "输入与表单",
        description: "文本框、多行文本、密码框与字段脚手架：标签、提示、说明与错误。",
      },
      pickers: { title: "选择器", description: "下拉选择、分段控件、开关、选项菜单与下拉菜单。" },
      toasts: {
        title: "提示弹窗",
        description: "完成操作后的弹出提示：成功、信息、注意与错误，按按钮触发。",
      },
      notices: { title: "提示条", description: "占据一行的提示：每种语气，带与不带操作。" },
      dialogs: { title: "对话框", description: "模态对话框、确认框、抽屉与底部面板。" },
      tooltips: {
        title: "悬停提示",
        description: "悬停与聚焦时出现的提示：data-tooltip 属性与 Tooltip 组件。",
      },
      tabs: { title: "标签页", description: "下划线式标签切换，可带更新标记。" },
      badges: {
        title: "徽标与状态",
        description: "徽标、运行状态图标、会话活动标记与更新点。",
      },
      empty: { title: "空状态", description: "列表或详情为空时的占位文字，可带操作。" },
      loading: { title: "加载", description: "转圈与骨架屏。" },
      charts: {
        title: "图表",
        description:
          "统计图的基础：所有图表共用的绘图原语、当前主题的图表令牌，以及建立在它们之上的每一种图表——环形图、趋势与用量柱、请求与成功率、活动与评分折线、轨迹时间线。",
      },
      avatars: { title: "头像", description: "用户头像与智能体头像的各个尺寸，以及头像组。" },
      files: { title: "文件", description: "文件树与只读文件浏览器。" },
      colour: {
        title: "颜色",
        description: "表面、文字、线条、强调色、语义色调、图表序列与代码色。",
      },
      type: { title: "字体排印", description: "各角色的字号、行高与字重。" },
      shape: { title: "形状", description: "圆角、阴影层级与嵌套。" },
      density: { title: "密度", description: "间距单位与控件高度。" },
      focus: { title: "焦点", description: "焦点环、输入框焦点、选区与滚动条。" },
      motion: { title: "动效", description: "进出、显现、布局与时长缓动。" },
      icons: { title: "图标", description: "图标尺寸与 Web App 的图标表。" },
      hooks: { title: "样式钩子", description: "主题可以重绘的结构钩子，逐个示范。" },
    } as Record<TopicId, { title: string; description: string }>,
    buttons: {
      variants: "变体",
      primary: "保存",
      secondary: "取消",
      danger: "删除",
      ghost: "更多",
      sizes: "尺寸",
      md: "默认尺寸",
      sm: "小尺寸",
      icon: "图标按钮",
      states: "状态",
      disabled: "已禁用",
      busy: "保存中…",
    },
    inputs: {
      basics: "文本框",
      name: "名称",
      namePlaceholder: "Docs Expert",
      nameHint: "在侧栏与消息中显示的名字。",
      email: "邮箱",
      emailValue: "zheng@example",
      emailError: "邮箱地址不完整。",
      required: "必填",
      info: "带说明",
      infoText: "改动在下一次 Task 开始时生效。",
      sizes: "尺寸",
      base: "基础尺寸",
      small: "表单尺寸",
      textarea: "多行文本",
      textareaPlaceholder: "写一段系统提示…",
      mono: "等宽",
      monoValue: "temperature: 0.2\nmax_tokens: 4096",
      password: "密码",
      passwordHint: "至少 12 个字符。",
    },
    pickers: {
      select: "下拉选择",
      selectLabel: "模型",
      options: ["DeepSeek V4.1 Flash", "Claude Sonnet 4.5", "GLM-5.3"] as readonly string[],
      segmented: "分段控件",
      segments: ["浅色", "深色", "跟随系统"] as readonly string[],
      switches: "开关",
      switchLabel: "完成时通知",
      switchHint: "Task 结束时弹出系统通知。",
      switchOff: "工具短名",
      optionMenu: "选项菜单",
      optionLabel: "权限",
      choices: [
        { value: "r", trigger: "r", label: "只读", description: "只能读取工作区。" },
        { value: "rw", trigger: "rw", label: "读写", description: "可以修改工作区里的文件。" },
        { value: "ask", trigger: "ask", label: "逐项审批", description: "每次写入前先询问。" },
      ] as readonly { value: string; trigger: string; label: string; description: string }[],
      dropdown: "下拉菜单",
      menu: "更多操作",
      menuItems: ["置顶", "重命名", "移动到…", "删除"] as readonly string[],
    },
    toasts: {
      fire: "触发一条提示",
      hint: "提示出现在页面顶部，几秒后自动消失；错误与注意会停留更久。",
      success: "成功",
      info: "信息",
      attention: "注意",
      error: "错误",
      successText: "已保存。",
      infoText: "索引正在后台重建。",
      attentionText: "已保存，但有 2 个字段被截断。",
      errorText: "连接失败：无法访问 api.example。",
    },
    notices: {
      plain: "每种语气",
      dotted: "带前导标记",
      withActions: "带操作",
      texts: {
        link: "新版本 0.3.0 可用。",
        success: "索引已重建，共 214 个文件。",
        busy: "正在同步语料库…",
        attention: "有 1 条未预期错误。",
        danger: "模型返回 401：密钥无效。",
        muted: "这个会话已归档。",
      },
      action: "查看",
      dismiss: "忽略",
    },
    dialogs: {
      modal: "模态对话框",
      openModal: "打开对话框",
      modalTitle: "重命名会话",
      modalBody: "新的名字会显示在侧栏与消息里。",
      save: "保存",
      cancel: "取消",
      confirm: "确认框",
      openConfirm: "删除会话…",
      confirmTitle: "删除这个会话？",
      confirmBody: "对话记录与 Trace 文件会一并删除，无法恢复。",
      confirmLabel: "删除",
      drawer: "抽屉",
      openDrawer: "打开抽屉",
      drawerTitle: "导航",
      drawerBody: "手机宽度下的侧栏从边缘滑入。",
      sheet: "底部面板",
      openSheet: "打开底部面板",
      sheetTitle: "文件",
      sheetBody: "向上拖动展开到整屏，向下拖动关闭。",
    },
    tooltips: {
      attribute: "data-tooltip 属性",
      attributeHint: "任何元素加上属性即可；只有图标的按钮同时带 aria-label。",
      component: "Tooltip 组件",
      componentHint: "需要包裹时使用：右侧或下方摆放。",
      truncated: "被截断的文本",
      truncatedHint: "行里放不下的命令或标题，完整内容放进提示里。",
      edit: "编辑",
      copy: "复制",
      settings: "设置",
      beside: "右侧",
      below: "下方",
      command:
        "pnpm --filter @prismshadow/penguin-web exec vitest run test/session-activity.test.ts --reporter verbose",
    },
    tabs: {
      basic: "标签切换",
      badged: "带更新标记",
      items: ["概览", "轨迹", "文件", "设置"] as readonly string[],
      badgeText: "有 3 个技能可更新",
      body: (tab: string) => `「${tab}」的内容。`,
    },
    badges: {
      badges: "徽标",
      tones: {
        gray: "默认",
        brand: "来源",
        green: "运行中",
        yellow: "免费",
        amber: "已中止",
        red: "失败",
      },
      status: "运行状态",
      states: {
        running: "运行中",
        waiting: "等待审批",
        done: "已完成",
        failed: "失败",
        stopped: "已停止",
      },
      activity: "会话活动",
      activities: { running: "运行中", compacting: "压缩中", completedUnread: "有未读回复" },
      marks: "其他标记",
      background: "后台任务",
      schedule: "定时任务",
      dot: "更新点",
      dotAnchor: "插件市场",
      pill: "更新提示",
      pillText: "3 个可更新",
    },
    empty: {
      page: "页面空状态",
      title: "还没有会话",
      description: "发送第一条消息后，会话会出现在这里。",
      action: "新对话",
      settings: "设置区空状态",
      settingsText: "还没有添加任何 MCP 服务器。",
    },
    loading: {
      spinner: "转圈",
      sizes: "三档尺寸",
      skeleton: "骨架屏",
      list: "列表",
      card: "卡片",
    },
    charts: {
      parts: {
        primitives: "绘图原语",
        primitivesHint:
          "每个图表都只通过这几个原语落笔：它们读取主题的图表令牌，写出 data-part，是令牌变成 SVG 或 HTML 的唯一地方。",
        tokens: "当前主题的图表令牌",
        tokensHint: "从这个框的根元素的计算样式读取；换主题、明暗或强调色后重新读取。",
        charts: "建立在原语上的图表",
        chartsHint: "应用里的每一种图表，使用演示数据。",
      },
      primitives: {
        bar: "ChartBar · 柱",
        barHint: "宽度由 bar-fill 决定，顶角圆角、边框与填充不透明度各按令牌。",
        line: "ChartLine · 折线",
        lineHint: "同一组点，按三种连线方式各画一次；线宽按令牌。",
        curves: { linear: "linear · 直连", smooth: "smooth · 平滑", step: "step · 阶梯" },
        area: "ChartArea · 面积",
        areaHint: "折线下方的填充，不透明度按令牌。",
        point: "ChartPoint · 数据点",
        pointHint: "半径按令牌；主题决定圆点还是方点。",
        arc: "ChartArc · 弧",
        arcHint: "环形图的一段：底环是 grid，各段按 Token 种类色或色槽。",
        grid: "ChartGrid 与 ChartAxis · 网格与坐标轴",
        gridHint: "网格线与坐标轴的墨色按令牌，主题决定实线或虚线。",
        timeline: "TimelineBar · 轨迹条",
        timelineHint: "轨迹时间线的 HTML 条，五种分段各取一个色槽。",
        kinds: {
          thinking: "思考",
          text: "回复",
          tool_call: "工具调用",
          approval: "等待审批",
          tool: "工具执行",
        },
      },
      palette: "调色板",
      geometry: "几何",
      tokenMeaning: {
        "--ui-chart-1": "色槽 1 · 紫",
        "--ui-chart-2": "色槽 2 · 琥珀",
        "--ui-chart-3": "色槽 3 · 天蓝",
        "--ui-chart-4": "色槽 4 · 玫红",
        "--ui-chart-5": "色槽 5 · 翠绿",
        "--ui-chart-6": "色槽 6 · 品红",
        "--ui-chart-7": "色槽 7 · 备用",
        "--ui-chart-8": "色槽 8 · 备用",
        "--ui-chart-ref": "参考线",
        "--ui-chart-cache-read": "缓存读取",
        "--ui-chart-cache-write": "缓存写入",
        "--ui-chart-output": "输出",
        "--ui-chart-grid": "网格线",
        "--ui-chart-axis": "坐标轴",
        "--ui-chart-bar-fill": "柱宽占带宽的比例（0–1）",
        "--ui-chart-bar-radius": "柱顶圆角",
        "--ui-chart-bar-stroke": "柱边框宽",
        "--ui-chart-bar-stroke-color": "柱边框色（series 即序列色）",
        "--ui-chart-bar-opacity": "柱填充不透明度（0–1）",
        "--ui-chart-line-width": "线宽",
        "--ui-chart-point-radius": "数据点半径",
        "--ui-chart-curve": "连线方式（linear / smooth / step）",
        "--ui-chart-area-opacity": "面积填充不透明度（0–1）",
      } as Record<ChartToken, string>,
      donut: "Token 环形图",
      donutHint: "缓存读取、缓存写入与输出的构成，环的余量随接近上限变色。",
      trend: "成本趋势",
      trendHint: "十四天的成本折线，悬停查看某一天。",
      tokens: "Token 用量",
      tokensHint: "按种类堆叠的每日 Token 柱，叠加缓存命中率曲线；悬停图例高亮一种。",
      requests: "请求与成功率",
      requestsHint: "按智能体堆叠的每日请求数，与各自的成功率线。",
      agents: ["docs-expert", "release-notes"] as readonly string[],
      activity: "活动折线",
      activityHint: "智能体卡片上的十四天会话数曲线，只看相对起伏。",
      sparkline: "评分折线",
      sparklineHint: "一个评估任务的历次得分，最新一次标出。",
      timeline: "轨迹时间线",
      timelineHint:
        "一次 Task 的模型分段与工具调用：思考、回复、工具调用、等待审批与执行，各占一道。",
    },
    avatars: {
      user: "用户头像",
      agent: "智能体头像",
      stack: "头像组",
      stackShown: (shown: number, total: number) => `共 ${total} 个，显示 ${shown} 个`,
      userNames: ["admin", "演示管理员"] as readonly string[],
      agents: [
        { id: "docs-expert", name: "Docs Expert" },
        { id: "release-notes", name: "Release Notes" },
        { id: "qa", name: "QA" },
      ] as readonly { id: string; name: string }[],
    },
    files: {
      tree: "文件树",
      treeLabel: "工作区",
      browser: "文件浏览器",
      header: "docs-expert",
      emptyPreview: "选择左侧的文件预览。",
      emptyDir: "空目录",
      readme:
        "# Docs Expert\n\n从 `corpus/` 建立 BM25 索引，回答关于 Claude Code 文档的问题。\n\n- `src/rag.ts` — 检索\n- `test/` — 用例",
    },
  },
};

export type GalleryStrings = typeof zh;
