/**
 * English gallery chrome copy, constrained by `GalleryStrings` to the shape of the Chinese
 * dictionary in strings.ts. Module and catalog titles and descriptions come from the module files
 * and catalog.ts themselves.
 */
import type { GalleryStrings } from "./strings";

export const en: GalleryStrings = {
  brand: {
    title: "Penguin UI",
  },
  site: {
    home: "Home",
    components: "Components",
    screens: "Screens",
    fonts: "Fonts",
    pages: "Pages",
    search: "Search modules",
    searchShortcut: "Ctrl K",
    noMatches: "No module matches.",
    modules: "Modules",
    onThisPage: "On this page",
    settings: "View settings",
    menu: "Open the menu",
    closeMenu: "Close the menu",
    notFound: (id) => `There is no module named “${id}”.`,
    allModules: "All modules",
    feedbackTitle: "Feedback",
    feedbackBody:
      "Quote the breadcrumb at the end of a preview's toolbar, or copy the section's address with the link button.",
    feedbackExample: "Frost › Conversation › Approval · dark",
  },
  groups: {
    foundations: "Foundations",
    conversation: "Conversation & composer",
    navigation: "Navigation & layout",
    actions: "Actions & feedback",
    forms: "Forms & overlays",
    data: "Data",
    content: "Content",
    flows: "Product flows",
    screens: "Screens",
  },
  home: {
    eyebrow: "Component gallery",
    title: "Penguin UI",
    lead: "Every module of the shared UI package, as a real interface in three themes, two modes, three root sizes and two languages.",
    shell: "The app shell",
    shellLead:
      "A real-proportion app window built from the modules' own compositions: switch the sidebar's pages, open a session, collapse the sidebar, type into the composer and send — laid out by each theme in its own way.",
    index: "Component index",
    indexLead: "One page per module: a section per variant, then its parts, tokens and source.",
  },
  rail: {
    theme: "Theme",
    themeNames: { github: "Primer", modern: "Frost", geek: "Console" },
    mode: "Mode",
    accent: "Accent",
    accentTheme: "Theme's own",
    size: "Size",
    language: "Language",
    viewport: "Viewport",
    viewports: { desktop: "Desktop", phone: "Phone" },
    langNames: { en: "EN", zh: "中文" },
    modes: { light: "Light", dark: "Dark", system: "System" },
    sizeTitle: (px) => `${px}px root`,
    compare: "Compare themes",
    reducedMotion: "Reduced motion",
  },
  crumb: {
    modes: { light: "light", dark: "dark" },
    phone: "phone",
  },
  intro: {
    resolving: "Resolving tokens…",
    problems: "Module and demo problems",
  },
  variant: {
    kinds: { animated: "Animation", interactive: "Interactive", static: "Still" },
    kindHints: {
      animated: "Press play to watch the scene; at rest it shows the settled state.",
      interactive: "Click and type in it; Reset returns it to its first state.",
      static: "A still.",
    },
    reset: "Reset",
    open: "Open standalone",
    compare: "Compare themes",
    compareOn: "Leave compare",
  },
  section: {
    copyLink: "Copy link",
    copied: "Copied",
    copyBreadcrumb: "Copy breadcrumb",
    parts: "Parts",
    tokens: "Tokens",
    source: "Source",
    variants: "Variants",
    tokensIn: (where, count) => `${count} tokens read, resolved in ${where}`,
    noTokens: "This composition reads no tokens.",
    unset: "unset",
    loadingCode: "Loading source…",
    compareFrame: (theme) => `${theme} preview`,
    partsOf: (count) => `${count} ${count === 1 ? "part" : "parts"}`,
    noParts: "This module lists no parts.",
    replaces: (what) => `replaces ${what}`,
  },
  transport: {
    label: "Playback",
    play: "Play",
    pause: "Pause",
    replay: "Replay",
    previous: "Previous frame",
    next: "Next frame",
    frames: "Frames",
    rate: "Speed",
  },
  embed: {
    unknownModule: (id) => `There is no module named “${id}”.`,
    noDemo: (id) => `“${id}” has no demo yet.`,
    nothing: "Name what to render with ?module=<module> or ?demo=<part>.",
  },
  screens: {
    open: "Open full screen",
    back: "Back to the Screens page",
    notFound: (name) => `There is no screen named “${name}”.`,
    descriptions: {},
  },
  foundations: {
    surfaces: "Surfaces",
    inks: "Inks",
    lines: "Lines",
    inkWords: ["Text", "Muted", "Subtle"],
    accent: "Accent",
    presetsHint:
      "The theme's own accent and the five presets this theme lists; another theme's presets paint nothing here",
    themeAccent: "theme",
    sampleSend: "Send",
    selectedRow: "Selected",
    sampleLink: "Open the docs",
    linkHover: "hover",
    tones: "Tones",
    toneWords: {
      success: "Running",
      attention: "Waiting",
      danger: "Failed",
      done: "Done",
      neutral: "Idle",
      info: "Syncing",
    },
    charts: "Chart series",
    tokenSeries: "Token mix",
    code: "Code and diff",
    codeLines: {
      before: "const hits = rank(q).slice(0, ",
      removed: "3",
      added: "6",
      after: ");",
      selected: "return cite(hits);",
    },
    typeNote:
      "Each row is set in its own role's tokens; the Chinese column shows how the theme's faces set Chinese with Latin runs in it.",
    scene: {
      pageTier: "page",
      cardTitle: "Docs Expert",
      cardMeta: "3 sessions · $0.0231",
      nested: "Inner radius = outer radius − padding",
      primary: "Save",
      secondary: "Cancel",
      input: "Search sessions",
      badge: "Running",
      menuTier: "z-[60] menu",
      menuItems: ["Pin", "Rename", "Move to…"],
      backdropTier: "z-50 dialog",
      dialogTitle: "Delete this session?",
      dialogBody: "Its transcript and Trace files are deleted with it.",
      cancel: "Cancel",
      confirm: "Delete",
      toastTier: "z-[100] toast",
      toast: "Exported Trace #001",
    },
    radius: "Radius",
    shadows: "Shadow levels",
    spacingPage: {
      title: "Settings",
      appearance: "Appearance",
      theme: "Theme",
      themeOptions: ["Light", "Dark", "System"],
      fontSize: "Font size",
      sizeOptions: ["S", "M", "L"],
      general: "General",
      language: "Language",
      languageOptions: ["中文", "English"],
      notifications: "Notify when done",
    },
    stack0Note: "stack-0: the narrow bars between a glyph and its label",
    controlHeights: "Control heights, measured",
    iconSizes: "Icon sizes",
    iconRegistry: (icons, files) => `${icons} icons from ${files} files`,
    duplicateNames: "One path, several names",
    durations: "Durations × easings",
    reducedNote: "Reduced motion: every change shows its end state at once.",
    liveSignal: "Live signals",
    loading: "Loading",
    focusRing: "Focus ring",
    inputFocus: "Input focus",
    selection: "Selection",
    scrollbar: "Scrollbar",
    spaceUnit: "Space unit",
    spaceUnitNote: "Every spacing and size utility is a multiple of it: h-8 is eight units.",
    shell: "Shell",
    shellNote:
      "The app window through .ui-shell: the field, the navigation column and the main column, related as each theme decides.",
    presence: "Presence",
    presenceNote:
      "A menu from the top, a dialog from the centre, a toast from the bottom — each on the active theme's enter and exit tokens.",
    reveal: "Reveal",
    revealNote:
      "Streamed text arrives chunk by chunk; each chunk moves once, on the reveal tokens, as it appears.",
    layout: "Layout",
    layoutNote: "The sidebar's width between expanded and rail, on the layout tokens.",
    replay: "Replay",
    replayAll: "Replay all",
    motionSpecimens: {
      menu: "Menu",
      dialog: "Dialog",
      toast: "Toast",
      trigger: "More",
      sidebarRows: ["New chat", "Agents", "Models"],
    },
    hookJobs: {
      "ui-glass": "a transient layer over content",
      "ui-eyebrow": "a group label naming the items below it",
      "ui-display": "the one display title of a page or hero",
      "ui-live": "motion for something running right now",
      "ui-frame": "a ruled box with a head, a body, a foot and panes",
      "ui-underline-nav": "the selected-tab marker of a tab bar",
      "ui-shell": "the app window: a navigation column beside a main column",
      "ui-icon-decor": "an icon its label already says: a theme may tint it or drop it",
      "ui-tree":
        "a list whose rows nest: a file tree, a work group's tool rows, the subagent graph",
      "ui-field": "a labelled control row: a form field or a settings row",
    },
    hookSamples: {
      menu: ["Pin", "Rename", "Delete"],
      group: "Workspaces",
      rows: ["claude-code-expert", "docs-sync", "release-notes"],
      copy: "Copy",
      tabs: ["Overview", "Traces", "Files"],
      streaming: "Writing the answer",
      tree: {
        root: "claude-code-expert",
        dir: "src",
        files: ["rag.ts", "embed.ts"],
        last: "README.md",
      },
      field: {
        name: "Name",
        value: "Docs Expert",
        hint: "Shown in the sidebar and in messages.",
        notify: "Notify when done",
        notifyHint: "A system notification when a Task ends.",
      },
    },
  },
  fonts: {
    title: "Fonts & licences",
    specimens: "Specimens",
    specimensHint: "Each theme's families, one en and one zh paragraph at 16 / 18 / 20 px.",
    declared: "Declared faces",
    declaredHint:
      "The @font-face rules in the page's stylesheets, merged by family, weight and style; a browser downloads a slice only when text uses it.",
    noFaces: "No faces declared.",
    family: "Family",
    weight: "Weight",
    slicesColumn: "Slices",
    loadStatus: "Loaded",
    licences: "Licence texts",
    noLicences: "No licence texts yet.",
    status: { loaded: "loaded", unloaded: "unused", loading: "loading", error: "failed" },
  },
  catalog: {
    modules: {},
    sections: {},
  },
};
