/**
 * PenguinHarness plugin library: the built-in plugins and the loader that reads them.
 *
 * A plugin is a directory under the package's `library/` carrying a `plugin.json` manifest and
 * any of two kinds of content: skills (`skills/<name>/SKILL.md`, installed into an Agent's
 * `agent_state/skills/`) and a hook package (`hooks/*.js`, installed into
 * `agent_state/hooks/<plugin>/` together with a generated `hooks.json`). The files are the
 * runtime source of truth — read and parsed on every call, no caching (files are small, calls
 * are infrequent) — so editing a file takes effect immediately. Only the category manifest
 * (id and titles) is code; install / uninstall / scan live in core's state layer.
 *
 * Versions are dates with a sequence number, `YYYY-MM-DD.N` (see PLUGIN_VERSION_PATTERN and
 * compareVersions). plugin.json is the single metadata holder: a library SKILL.md's frontmatter
 * carries only `name` and `description`, and the loader stamps the plugin's version and UI short
 * descriptions into each skill's metadata and installable content (the installed copy carries the
 * full frontmatter, generated — the way hooks.json is).
 *
 * Docs: packages/docs/content/skills.{zh,en}.md (site path /docs/skills) documents the plugin
 * format, the versions and the built-in library.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** A skill's metadata. A library SKILL.md's frontmatter carries only `name` and `description`; the short descriptions and `version` are stamped from plugin.json by the loader (installed copies then carry the full generated frontmatter, which is what the installed-side readers parse). */
export interface SkillMetadata {
  /** Skill name (matches its containing directory name). */
  name: string;
  /** One-line description; injected into the model prompt via `{{SKILL_METADATA}}`. */
  description: string;
  /** UI short description (frontmatter `short_description`, optional): preferred in compact spots like cards, falls back to the full description if missing; not injected into the prompt. */
  shortDescription?: string;
  /** Chinese short description (frontmatter `short_description_zh`, optional). */
  shortDescriptionZh?: string;
  /** Version, `YYYY-MM-DD.N`; an absent or malformed frontmatter version reads as "" (older than any real version). */
  version: string;
}

/** A skill in the library: metadata + full SKILL.md content (including frontmatter, written as-is on install). */
export interface LibrarySkill extends SkillMetadata {
  content: string;
  /** Optional raw `icon.svg` content in the directory (custom icon, the file is the sole source, copied alongside SKILL.md on install); absent means none (frontend falls back to the default book icon). */
  icon?: string;
  /**
   * Optional auxiliary files the SKILL.md references (e.g. `reference/API.md`), keyed by
   * POSIX-relative path within the skill directory; every entry except the top-level SKILL.md and
   * icon.svg, which have their own fields. Written alongside SKILL.md on install (subdirectories
   * preserved). Read as UTF-8 text — library content is committed text; the field is omitted when
   * a skill has no extra files.
   */
  files?: Record<string, string>;
}

/** One hook script entry: `command` is a path relative to the plugin's `hooks/` directory, run with Node; `timeout` in seconds (core's default applies when absent). */
export interface HookCommand {
  command: string;
  timeout?: number;
}

/**
 * The manifest an installed hook package carries (`agent_state/hooks/<plugin>/hooks.json`),
 * generated by the installer from plugin.json: identity and display fields, plus one script
 * list per hook point. `stop` is the only point today.
 */
export interface HookManifest {
  name: string;
  description: string;
  descriptionZh?: string;
  version: string;
  stop: HookCommand[];
}

/** A plugin's hook package as read from the library: the manifest to install and the `hooks/` files (relative path → text). */
export interface LibraryHooks {
  manifest: HookManifest;
  files: Record<string, string>;
}

/** A plugin in the library: the manifest fields plus the content it ships. */
export interface LibraryPlugin {
  /** Plugin name (its directory name). */
  name: string;
  /** English one-line description (plugin.json `description`, falling back to the first skill's description). */
  description: string;
  /** Chinese description (plugin.json `description_zh`, optional). */
  descriptionZh?: string;
  /** UI short descriptions (plugin.json, falling back to the first skill's). */
  shortDescription?: string;
  shortDescriptionZh?: string;
  /** `YYYY-MM-DD.N`. */
  version: string;
  /** Category id (see PLUGIN_CATEGORIES); absent or unknown → the "other" group. */
  category?: string;
  /** Whether default_agent gets this plugin at creation (plugin.json `preinstall`, default true). */
  preinstall: boolean;
  skills: LibrarySkill[];
  hooks?: LibraryHooks;
}

/** Category manifest entry: id and titles (Chinese optional, displayed per UI language). */
export interface PluginCategory {
  id: string;
  title: string;
  titleZh?: string;
}

/** Grouping result: category metadata + member plugins read from library files. */
export interface ResolvedPluginGroup extends PluginCategory {
  plugins: LibraryPlugin[];
}

/** Character rule for plugin, skill and hook names (directory names): prevents path traversal (exported for the server's archive-install validation). */
export const PLUGIN_NAME_PATTERN = /^[A-Za-z0-9_-]+$/;
/** Same rule under its historical name: skill directories follow it too. */
export const SKILL_NAME_PATTERN = PLUGIN_NAME_PATTERN;

/** Version format: an ISO date and a sequence number, e.g. `2026-08-29.1`. */
export const PLUGIN_VERSION_PATTERN = /^\d{4}-\d{2}-\d{2}\.\d+$/;

/**
 * Orders two versions: by date, then by sequence number (numeric, so `.10` follows `.9`). A
 * string that is not a version (the empty string an unversioned install reads as, a legacy
 * natural number) sorts before every real version, so anything in the library counts as newer.
 */
export function compareVersions(a: string, b: string): number {
  const va = PLUGIN_VERSION_PATTERN.test(a);
  const vb = PLUGIN_VERSION_PATTERN.test(b);
  if (!va || !vb) return Number(va) - Number(vb);
  const [da, na] = a.split(".");
  const [db, nb] = b.split(".");
  if (da !== db) return da! < db! ? -1 : 1;
  return Number(na) - Number(nb);
}

/**
 * Parses the frontmatter at the start of SKILL.md: only recognizes `key: value` lines inside the
 * first `---` block (split on the first colon, value trimmed, values may themselves contain colons);
 * all fields are scalars, no YAML dependency needed.
 * Error tolerance: returns null if the `---` block or name is missing; a version that is not
 * `YYYY-MM-DD.N` reads as "".
 */
export function parseSkillFrontmatter(content: string): SkillMetadata | null {
  // Strip a possible UTF-8 BOM (may be introduced by editors when manually editing an installed SKILL.md); CRLF is handled by \r?\n.
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(content.replace(/^﻿/, ""));
  if (!match) return null;
  const fields: Record<string, string> = {};
  for (const line of match[1]!.split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx <= 0) continue;
    const key = line.slice(0, idx).trim();
    if (key) fields[key] = line.slice(idx + 1).trim();
  }
  const name = fields["name"];
  if (!name) return null;
  const version = fields["version"] ?? "";
  const shortDescription = fields["short_description"];
  const shortDescriptionZh = fields["short_description_zh"];
  return {
    name,
    description: fields["description"] ?? "",
    // short_description(_zh) is optional: omitted when absent (undefined keys aren't set).
    ...(shortDescription !== undefined ? { shortDescription } : {}),
    ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
    version: PLUGIN_VERSION_PATTERN.test(version) ? version : "",
  };
}

/** Root directory of library files: the package's `library/` (both dist/ and src/ sit one level below the package root, so one level up reaches it). */
const PLUGINS_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "library");

/**
 * Recursively collects a directory's files as text keyed by POSIX-relative path, skipping the
 * names in `except` at the top level. Symlinks and other non-regular entries are skipped.
 * Returns undefined when the directory has no such files.
 */
function readDirFiles(dir: string, except: readonly string[]): Record<string, string> | undefined {
  const files: Record<string, string> = {};
  const walk = (abs: string, rel: string): void => {
    for (const entry of fs.readdirSync(abs, { withFileTypes: true })) {
      const childRel = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(path.join(abs, entry.name), childRel);
      } else if (entry.isFile()) {
        if (rel === "" && except.includes(entry.name)) continue;
        files[childRel] = fs.readFileSync(path.join(abs, entry.name), "utf8");
      }
    }
  };
  walk(dir, "");
  return Object.keys(files).length > 0 ? files : undefined;
}

/**
 * Reads one skill directory: name from the directory (overriding frontmatter), SKILL.md verbatim,
 * the optional icon.svg, and every other file as auxiliary content. Undefined without a SKILL.md.
 */
function readSkillDir(dir: string, name: string): LibrarySkill | undefined {
  let content: string;
  try {
    content = fs.readFileSync(path.join(dir, "SKILL.md"), "utf8");
  } catch {
    return undefined;
  }
  let icon: string | undefined;
  try {
    icon = fs.readFileSync(path.join(dir, "icon.svg"), "utf8");
  } catch {
    // icon.svg is optional: no custom icon if missing.
  }
  const files = readDirFiles(dir, ["SKILL.md", "icon.svg"]);
  const meta = parseSkillFrontmatter(content) ?? { name, description: "", version: "" };
  return {
    ...meta,
    name,
    content,
    ...(icon !== undefined ? { icon } : {}),
    ...(files !== undefined ? { files } : {}),
  };
}

/**
 * Resolves a library skill against its plugin's manifest: the plugin's version and UI short
 * descriptions fill the metadata (a library SKILL.md carries only `name` and `description`),
 * and the installable `content` gets the full frontmatter regenerated in canonical field
 * order — the installed copy is self-describing (update checks read its `version`, the UI its
 * short descriptions) the same way an installed hook package's hooks.json is generated.
 */
function stampSkill(
  skill: LibrarySkill,
  plugin: { shortDescription?: string; shortDescriptionZh?: string; version: string },
): LibrarySkill {
  const shortDescription = skill.shortDescription ?? plugin.shortDescription;
  const shortDescriptionZh = skill.shortDescriptionZh ?? plugin.shortDescriptionZh;
  const front = [
    "---",
    `name: ${skill.name}`,
    `description: ${skill.description}`,
    ...(shortDescription !== undefined ? [`short_description: ${shortDescription}`] : []),
    ...(shortDescriptionZh !== undefined ? [`short_description_zh: ${shortDescriptionZh}`] : []),
    `version: ${plugin.version}`,
    "---",
  ].join("\n");
  const body = skill.content.replace(/^\ufeff?---\r?\n[\s\S]*?\r?\n---/, "");
  return {
    ...skill,
    ...(shortDescription !== undefined ? { shortDescription } : {}),
    ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
    version: plugin.version,
    content: `${front}${body}`,
  };
}

/** The raw plugin.json shape (every field optional; the loader fills the defaults). */
interface PluginManifestFile {
  description?: string;
  description_zh?: string;
  short_description?: string;
  short_description_zh?: string;
  version?: string;
  category?: string;
  preinstall?: boolean;
  hooks?: { stop?: Array<{ command?: string; timeout?: number }> };
}

/** Reads one plugin directory; undefined without a parseable plugin.json. */
function readPluginDir(name: string): LibraryPlugin | undefined {
  const dir = path.join(PLUGINS_ROOT, name);
  let manifest: PluginManifestFile;
  try {
    manifest = JSON.parse(
      fs.readFileSync(path.join(dir, "plugin.json"), "utf8"),
    ) as PluginManifestFile;
  } catch {
    return undefined;
  }
  if (manifest === null || typeof manifest !== "object") return undefined;
  const skills: LibrarySkill[] = [];
  const skillsDir = path.join(dir, "skills");
  if (fs.existsSync(skillsDir)) {
    for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const skill = readSkillDir(path.join(skillsDir, entry.name), entry.name);
      if (skill) skills.push(skill);
    }
    skills.sort((a, b) => a.name.localeCompare(b.name));
  }
  const first = skills[0];
  const description =
    typeof manifest.description === "string" ? manifest.description : (first?.description ?? "");
  const shortDescription =
    typeof manifest.short_description === "string"
      ? manifest.short_description
      : first?.shortDescription;
  const shortDescriptionZh =
    typeof manifest.short_description_zh === "string"
      ? manifest.short_description_zh
      : first?.shortDescriptionZh;
  const version =
    typeof manifest.version === "string" && PLUGIN_VERSION_PATTERN.test(manifest.version)
      ? manifest.version
      : "";
  const stop = (manifest.hooks?.stop ?? [])
    .filter((c): c is { command: string; timeout?: number } => typeof c?.command === "string")
    .map((c) => ({
      command: c.command,
      ...(typeof c.timeout === "number" ? { timeout: c.timeout } : {}),
    }));
  const hooksDir = path.join(dir, "hooks");
  const hookFiles = fs.existsSync(hooksDir) ? readDirFiles(hooksDir, []) : undefined;
  const hooks: LibraryHooks | undefined =
    hookFiles !== undefined
      ? {
          manifest: {
            name,
            description,
            ...(typeof manifest.description_zh === "string"
              ? { descriptionZh: manifest.description_zh }
              : {}),
            version,
            stop,
          },
          files: hookFiles,
        }
      : undefined;
  return {
    name,
    description,
    ...(typeof manifest.description_zh === "string"
      ? { descriptionZh: manifest.description_zh }
      : {}),
    ...(shortDescription !== undefined ? { shortDescription } : {}),
    ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
    version,
    ...(typeof manifest.category === "string" ? { category: manifest.category } : {}),
    preinstall: manifest.preinstall !== false,
    skills: skills.map((skill) =>
      stampSkill(skill, {
        ...(shortDescription !== undefined ? { shortDescription } : {}),
        ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
        version,
      }),
    ),
    ...(hooks !== undefined ? { hooks } : {}),
  };
}

/** Reads every plugin in the library (one per subdirectory under `library/` with a plugin.json), sorted by name. */
export function loadLibraryPlugins(): LibraryPlugin[] {
  const plugins: LibraryPlugin[] = [];
  for (const entry of fs.readdirSync(PLUGINS_ROOT, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const plugin = readPluginDir(entry.name);
    if (plugin) plugins.push(plugin);
  }
  return plugins.sort((a, b) => a.name.localeCompare(b.name));
}

/** The plugins default_agent installs at initialization: every library plugin except those whose manifest sets `preinstall: false`. */
export function loadPreinstalledPlugins(): LibraryPlugin[] {
  return loadLibraryPlugins().filter((plugin) => plugin.preinstall);
}

/** Reads a single library plugin by name; undefined when the name has illegal characters (path traversal guard) or the plugin doesn't exist. */
export function libraryPlugin(name: string): LibraryPlugin | undefined {
  if (!PLUGIN_NAME_PATTERN.test(name)) return undefined;
  return readPluginDir(name);
}

/** Finds a library skill by its own name (across every plugin), with the plugin that ships it. */
export function librarySkill(
  name: string,
): { plugin: LibraryPlugin; skill: LibrarySkill } | undefined {
  if (!PLUGIN_NAME_PATTERN.test(name)) return undefined;
  for (const plugin of loadLibraryPlugins()) {
    const skill = plugin.skills.find((s) => s.name === name);
    if (skill) return { plugin, skill };
  }
  return undefined;
}

/**
 * Category manifest, in display order. Categories group by audience, not by technology; the
 * session-hooks category holds the plugins that ship hook packages.
 * Docs: /docs/skills § "Built-in library".
 */
export const PLUGIN_CATEGORIES: PluginCategory[] = [
  { id: "office-productivity", title: "Office Productivity", titleZh: "办公效率" },
  { id: "software-development", title: "Software Development", titleZh: "软件开发" },
  { id: "ai-app-development", title: "AI App Development", titleZh: "AI 应用开发" },
  { id: "agent-tuning", title: "Agent Tuning", titleZh: "Agent 调优" },
  { id: "session-hooks", title: "Session Hooks", titleZh: "会话钩子" },
];

/**
 * Groups plugins by category in PLUGIN_CATEGORIES order (members sorted by name; an empty
 * category is omitted); plugins with no or an unknown category land in an Other group appended
 * at the end (only when non-empty). A pure function, the testable core of loadPluginGroups.
 */
export function groupPlugins(all: LibraryPlugin[]): ResolvedPluginGroup[] {
  const groups: ResolvedPluginGroup[] = [];
  const known = new Set(PLUGIN_CATEGORIES.map((c) => c.id));
  for (const category of PLUGIN_CATEGORIES) {
    const members = all
      .filter((p) => p.category === category.id)
      .sort((a, b) => a.name.localeCompare(b.name));
    if (members.length > 0) groups.push({ ...category, plugins: members });
  }
  const others = all
    .filter((p) => p.category === undefined || !known.has(p.category))
    .sort((a, b) => a.name.localeCompare(b.name));
  if (others.length > 0) {
    groups.push({ id: "other", title: "Other", titleZh: "其他", plugins: others });
  }
  return groups;
}

/** Reads the library and groups it (see groupPlugins). */
export function loadPluginGroups(): ResolvedPluginGroup[] {
  return groupPlugins(loadLibraryPlugins());
}
