#!/usr/bin/env node
// a2ui-sources-sha256: a3b12dbe6d30ef4b36393781206b3dc2f3ff2ac6eb5e7c754302ab7b6690bf30
// Generated by scripts/build-a2ui-check.mjs (pnpm build:a2ui-check) from packages/core/src/a2ui/*.ts. Do not edit; rebuild.

// packages/core/src/a2ui/cli.ts
import { readFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

// packages/core/src/a2ui/types.ts
var A2UI_LIMITS = {
  /** `id` of a choice or form. */
  idPattern: /^[a-z][a-z0-9_-]{0,31}$/,
  /** `id` of a form field (no hyphen: it doubles as an answer key). */
  fieldIdPattern: /^[a-z][a-z0-9_]{0,31}$/,
  question: 120,
  label: 60,
  labelWarn: 40,
  value: 500,
  description: 160,
  options: { min: 2, max: 7, warn: 5 },
  fields: { min: 1, max: 6, warn: 4 },
  steps: { min: 1, max: 15, warn: 10 },
  title: 80,
  placeholder: 80,
  unit: 12,
  submitLabel: 24,
  stepText: 200,
  stepCode: 2e3,
  lang: 20,
  calloutText: 400,
  mermaid: { statements: 30, lines: 400 }
};
var A2UI_SCORING = {
  l2PerWarning: 15,
  prosePerWarning: 5,
  l2Weight: 0.5,
  proseWeight: 0.5,
  passTotal: 70
};

// packages/core/src/a2ui/catalog.ts
var isObj = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
var join = (path2, key) => path2 === "" ? key : `${path2}.${key}`;
var length = (s) => [...s].length;
var Issues = class {
  list = [];
  error(code, message, path2, line) {
    this.push("error", code, message, path2, line);
  }
  warn(code, message, path2) {
    this.push("warning", code, message, path2);
  }
  get hasError() {
    return this.list.some((issue2) => issue2.level === "error");
  }
  push(level, code, message, path2, line) {
    const issue2 = { level, code, message };
    if (path2 !== void 0) issue2.path = path2;
    if (line !== void 0) issue2.line = line;
    this.list.push(issue2);
  }
};
function readString(is, obj, key, path2, rule) {
  const value = obj[key];
  const p = join(path2, key);
  if (value === void 0 || value === null) {
    if (rule.required) is.error("missing_field", `\`${p}\` is required.`, p);
    return void 0;
  }
  if (typeof value !== "string") {
    is.error("wrong_type", `\`${p}\` must be a string.`, p);
    return void 0;
  }
  if (value.trim() === "") {
    if (rule.required) {
      is.error("empty_string", `\`${p}\` is empty; write the text or drop the block.`, p);
    }
    return void 0;
  }
  const n = length(value);
  if (n > rule.max) {
    is.error(
      "too_long",
      `\`${p}\` is ${n} characters; the limit is ${rule.max}. Shorten it or move the detail into the prose.`,
      p
    );
  }
  if (rule.pattern && !rule.pattern.test(value)) {
    is.error(
      "invalid_format",
      `\`${p}\` must match ${rule.pattern.source}${rule.patternHint ? ` (${rule.patternHint})` : ""}.`,
      p
    );
  }
  return value;
}
function readBoolean(is, obj, key, path2) {
  const value = obj[key];
  if (value === void 0 || value === null) return void 0;
  if (typeof value !== "boolean") {
    is.error("wrong_type", `\`${join(path2, key)}\` must be true or false.`, join(path2, key));
    return void 0;
  }
  return value;
}
function readNumber(is, obj, key, path2) {
  const value = obj[key];
  if (value === void 0 || value === null) return void 0;
  if (typeof value !== "number" || !Number.isFinite(value)) {
    is.error("wrong_type", `\`${join(path2, key)}\` must be a number.`, join(path2, key));
    return void 0;
  }
  return value;
}
function readEnum(is, obj, key, path2, values) {
  const value = obj[key];
  const p = join(path2, key);
  if (value === void 0 || value === null) {
    is.error("missing_field", `\`${p}\` is required: one of ${values.join(", ")}.`, p);
    return void 0;
  }
  if (typeof value !== "string" || !values.includes(value)) {
    is.error("invalid_enum", `\`${p}\` must be one of ${values.join(", ")}.`, p);
    return void 0;
  }
  return value;
}
function readArray(is, obj, key, path2, rule) {
  const value = obj[key];
  const p = join(path2, key);
  if (value === void 0 || value === null) {
    is.error("missing_field", `\`${p}\` is required.`, p);
    return void 0;
  }
  if (!Array.isArray(value)) {
    is.error("wrong_type", `\`${p}\` must be an array.`, p);
    return void 0;
  }
  if (value.length < rule.min || value.length > rule.max) {
    is.error(
      "count_out_of_range",
      `\`${p}\` has ${value.length} ${rule.what}; allowed ${rule.min}\u2013${rule.max}. ${value.length < rule.min ? "Add more, or answer in prose." : "Cut to the realistic ones, or split into two turns."}`,
      p
    );
  } else if (rule.warn !== void 0 && rule.warnCode && value.length > rule.warn) {
    is.warn(
      rule.warnCode,
      `\`${p}\` has ${value.length} ${rule.what}; more than ${rule.warn} is hard to take in at a glance.`,
      p
    );
  }
  return value;
}
function unknownFields(is, obj, known, path2, what) {
  for (const key of Object.keys(obj)) {
    if (known.includes(key)) continue;
    const p = join(path2, key);
    is.warn("unknown_field", `\`${p}\` is not a field of ${what}; it is ignored.`, p);
  }
}
var OPTION_FIELDS = ["label", "value", "description", "recommended"];
function parseOptions(is, obj, key, path2) {
  const raw = readArray(is, obj, key, path2, {
    ...A2UI_LIMITS.options,
    warnCode: "too_many_options",
    what: "options"
  });
  if (raw === void 0) return void 0;
  const p = join(path2, key);
  const options = [];
  const labels = /* @__PURE__ */ new Map();
  let recommended = 0;
  raw.forEach((item, i) => {
    const ip = `${p}[${i}]`;
    if (!isObj(item)) {
      is.error("wrong_type", `\`${ip}\` must be an object with a \`label\`.`, ip);
      return;
    }
    const label = readString(is, item, "label", ip, { required: true, max: A2UI_LIMITS.label });
    const value = readString(is, item, "value", ip, { max: A2UI_LIMITS.value });
    const description = readString(is, item, "description", ip, {
      max: A2UI_LIMITS.description
    });
    const rec = readBoolean(is, item, "recommended", ip);
    unknownFields(is, item, OPTION_FIELDS, ip, "an option");
    if (rec === true) recommended++;
    if (label === void 0) return;
    if (length(label) > A2UI_LIMITS.labelWarn) {
      is.warn(
        "option_label_long",
        `\`${ip}.label\` is longer than ${A2UI_LIMITS.labelWarn} characters; keep labels short and put the detail in \`description\`.`,
        `${ip}.label`
      );
    }
    const seen = labels.get(label);
    if (seen !== void 0) {
      is.error(
        "duplicate_label",
        `\`${ip}.label\` repeats option ${seen + 1}'s label "${label}"; labels must be unique.`,
        `${ip}.label`
      );
    } else {
      labels.set(label, i);
    }
    const option = { label };
    if (value !== void 0) option.value = value;
    if (description !== void 0) option.description = description;
    if (rec !== void 0) option.recommended = rec;
    options.push(option);
  });
  if (recommended > 1) {
    is.error(
      "multiple_recommended",
      `\`${p}\` marks ${recommended} options as recommended; at most one may be.`,
      p
    );
  }
  return options;
}
var ID_HINT = "lower-case letters, digits, _ or -, starting with a letter, at most 32";
var CHOICE_FIELDS = ["type", "id", "question", "options", "multiple", "allowOther"];
function parseChoice(is, obj) {
  const id = readString(is, obj, "id", "", {
    max: 32,
    pattern: A2UI_LIMITS.idPattern,
    patternHint: ID_HINT
  });
  const question = readString(is, obj, "question", "", {
    required: true,
    max: A2UI_LIMITS.question
  });
  const options = parseOptions(is, obj, "options", "");
  const multiple = readBoolean(is, obj, "multiple", "");
  const allowOther = readBoolean(is, obj, "allowOther", "");
  unknownFields(is, obj, CHOICE_FIELDS, "", "a choice");
  if (question === void 0 || options === void 0) return void 0;
  const spec = { type: "choice", question, options };
  if (id !== void 0) spec.id = id;
  if (multiple !== void 0) spec.multiple = multiple;
  if (allowOther !== void 0) spec.allowOther = allowOther;
  return spec;
}
var FIELD_KINDS = ["single", "multiple", "text", "number"];
var FIELD_FIELDS = [
  "id",
  "label",
  "kind",
  "options",
  "placeholder",
  "min",
  "max",
  "step",
  "unit",
  "required"
];
var NUMBER_ONLY = ["min", "max", "step", "unit"];
var FORM_FIELDS = ["type", "id", "title", "fields", "submitLabel"];
function parseFormField(is, item, fp) {
  if (!isObj(item)) {
    is.error("wrong_type", `\`${fp}\` must be an object with \`id\`, \`label\` and \`kind\`.`, fp);
    return void 0;
  }
  const id = readString(is, item, "id", fp, {
    required: true,
    max: 32,
    pattern: A2UI_LIMITS.fieldIdPattern,
    patternHint: "lower-case letters, digits or _, starting with a letter, at most 32"
  });
  const label = readString(is, item, "label", fp, { required: true, max: A2UI_LIMITS.label });
  const kind = readEnum(is, item, "kind", fp, FIELD_KINDS);
  const hasOptions = item.options !== void 0 && item.options !== null;
  let options;
  if (kind === "single" || kind === "multiple") {
    if (!hasOptions) {
      is.error(
        "options_required",
        `\`${fp}.options\` is required for kind "${kind}".`,
        `${fp}.options`
      );
    } else {
      options = parseOptions(is, item, "options", fp);
    }
  } else if (kind !== void 0 && hasOptions) {
    is.error(
      "options_forbidden",
      `\`${fp}.options\` is not allowed for kind "${kind}"; use kind "single" or "multiple" to offer options.`,
      `${fp}.options`
    );
  }
  const placeholder = readString(is, item, "placeholder", fp, { max: A2UI_LIMITS.placeholder });
  if (placeholder !== void 0 && (kind === "single" || kind === "multiple")) {
    is.warn(
      "ignored_field",
      `\`${fp}.placeholder\` has no effect on kind "${kind}"; it is ignored.`,
      `${fp}.placeholder`
    );
  }
  const min = readNumber(is, item, "min", fp);
  const max = readNumber(is, item, "max", fp);
  const step = readNumber(is, item, "step", fp);
  const unit = readString(is, item, "unit", fp, { max: A2UI_LIMITS.unit });
  if (kind !== void 0 && kind !== "number") {
    for (const key of NUMBER_ONLY) {
      if (item[key] !== void 0 && item[key] !== null) {
        is.error(
          "number_only",
          `\`${fp}.${key}\` is only valid for kind "number"; remove it or change the kind.`,
          `${fp}.${key}`
        );
      }
    }
  }
  if (min !== void 0 && max !== void 0 && min > max) {
    is.error("range_invalid", `\`${fp}\`: min ${min} is greater than max ${max}.`, `${fp}.min`);
  }
  if (step !== void 0 && step <= 0) {
    is.error("range_invalid", `\`${fp}.step\` must be greater than 0.`, `${fp}.step`);
  }
  const required = readBoolean(is, item, "required", fp);
  unknownFields(is, item, FIELD_FIELDS, fp, "a form field");
  if (id === void 0 || label === void 0 || kind === void 0) return void 0;
  const field = { id, label, kind };
  if (options !== void 0) field.options = options;
  if (placeholder !== void 0) field.placeholder = placeholder;
  if (min !== void 0) field.min = min;
  if (max !== void 0) field.max = max;
  if (step !== void 0) field.step = step;
  if (unit !== void 0) field.unit = unit;
  if (required !== void 0) field.required = required;
  return field;
}
function parseForm(is, obj) {
  const id = readString(is, obj, "id", "", {
    max: 32,
    pattern: A2UI_LIMITS.idPattern,
    patternHint: ID_HINT
  });
  const title = readString(is, obj, "title", "", { max: A2UI_LIMITS.title });
  const raw = readArray(is, obj, "fields", "", {
    ...A2UI_LIMITS.fields,
    warnCode: "form_too_many_fields",
    what: "fields"
  });
  const submitLabel = readString(is, obj, "submitLabel", "", { max: A2UI_LIMITS.submitLabel });
  unknownFields(is, obj, FORM_FIELDS, "", "a form");
  if (raw === void 0) return void 0;
  const fields = [];
  const ids = /* @__PURE__ */ new Map();
  raw.forEach((item, i) => {
    const field = parseFormField(is, item, `fields[${i}]`);
    if (field === void 0) return;
    const seen = ids.get(field.id);
    if (seen !== void 0) {
      is.error(
        "duplicate_id",
        `\`fields[${i}].id\` repeats field ${seen + 1}'s id "${field.id}"; ids must be unique.`,
        `fields[${i}].id`
      );
    } else {
      ids.set(field.id, i);
    }
    fields.push(field);
  });
  const spec = { type: "form", fields };
  if (id !== void 0) spec.id = id;
  if (title !== void 0) spec.title = title;
  if (submitLabel !== void 0) spec.submitLabel = submitLabel;
  return spec;
}
var STEP_FIELDS = ["text", "warning", "caution", "note", "code", "lang"];
var STEPS_FIELDS = ["type", "title", "steps"];
function parseSteps(is, obj) {
  const title = readString(is, obj, "title", "", { max: A2UI_LIMITS.title });
  const raw = readArray(is, obj, "steps", "", {
    ...A2UI_LIMITS.steps,
    warnCode: "steps_too_many",
    what: "steps"
  });
  unknownFields(is, obj, STEPS_FIELDS, "", "a steps block");
  if (raw === void 0) return void 0;
  const steps = [];
  raw.forEach((item, i) => {
    const sp = `steps[${i}]`;
    if (!isObj(item)) {
      is.error("wrong_type", `\`${sp}\` must be an object with a \`text\`.`, sp);
      return;
    }
    const text = readString(is, item, "text", sp, { required: true, max: A2UI_LIMITS.stepText });
    const warning = readString(is, item, "warning", sp, { max: A2UI_LIMITS.stepText });
    const caution = readString(is, item, "caution", sp, { max: A2UI_LIMITS.stepText });
    const note = readString(is, item, "note", sp, { max: A2UI_LIMITS.stepText });
    const code = readString(is, item, "code", sp, { max: A2UI_LIMITS.stepCode });
    const lang = readString(is, item, "lang", sp, { max: A2UI_LIMITS.lang });
    if (lang !== void 0 && code === void 0) {
      is.warn("ignored_field", `\`${sp}.lang\` without \`code\` has no effect.`, `${sp}.lang`);
    }
    unknownFields(is, item, STEP_FIELDS, sp, "a step");
    if (text === void 0) return;
    const step = { text };
    if (warning !== void 0) step.warning = warning;
    if (caution !== void 0) step.caution = caution;
    if (note !== void 0) step.note = note;
    if (code !== void 0) step.code = code;
    if (lang !== void 0) step.lang = lang;
    steps.push(step);
  });
  const spec = { type: "steps", steps };
  if (title !== void 0) spec.title = title;
  return spec;
}
var TONES = ["note", "tip", "caution", "warning"];
var CALLOUT_FIELDS = ["type", "tone", "title", "text"];
function parseCallout(is, obj) {
  const tone = readEnum(is, obj, "tone", "", TONES);
  const title = readString(is, obj, "title", "", { max: A2UI_LIMITS.title });
  const text = readString(is, obj, "text", "", { required: true, max: A2UI_LIMITS.calloutText });
  unknownFields(is, obj, CALLOUT_FIELDS, "", "a callout");
  if (tone === void 0 || text === void 0) return void 0;
  const spec = { type: "callout", tone, text };
  if (title !== void 0) spec.title = title;
  return spec;
}
function stripTrailingCommas(text) {
  let out = "";
  let inString = false;
  let changed = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i] ?? "";
    if (inString) {
      out += ch;
      if (ch === "\\") {
        out += text[i + 1] ?? "";
        i++;
      } else if (ch === '"') {
        inString = false;
      }
      continue;
    }
    if (ch === '"') {
      inString = true;
      out += ch;
      continue;
    }
    if (ch === ",") {
      let j = i + 1;
      while (j < text.length && /\s/.test(text[j] ?? "")) j++;
      const next = text[j];
      if (next === "}" || next === "]") {
        changed = true;
        continue;
      }
    }
    out += ch;
  }
  return { text: out, changed };
}
function errorLine(err, text) {
  const message = err instanceof Error ? err.message : String(err);
  const m = /position (\d+)/.exec(message);
  if (!m) return void 0;
  const pos = Math.min(Number(m[1]), text.length);
  return text.slice(0, pos).split("\n").length;
}
function parseA2ui(source) {
  const is = new Issues();
  const text = source.replace(/\r\n?/g, "\n");
  if (text.trim() === "") {
    is.error("empty_block", "The a2ui fence is empty; it must hold one JSON object.");
    return { issues: is.list };
  }
  let data;
  try {
    data = JSON.parse(text);
  } catch (err) {
    const lenient = stripTrailingCommas(text);
    let recovered = false;
    if (lenient.changed) {
      try {
        data = JSON.parse(lenient.text);
        recovered = true;
      } catch {
      }
    }
    if (!recovered) {
      const detail = err instanceof Error ? err.message : String(err);
      is.error(
        "invalid_json",
        `The block is not valid JSON (${detail}). Write one strict JSON object: double quotes, no comments, no trailing commas.`,
        void 0,
        errorLine(err, text)
      );
      return { issues: is.list };
    }
    is.warn(
      "json_trailing_comma",
      "A trailing comma was tolerated this time; strict JSON has none."
    );
  }
  if (!isObj(data)) {
    is.error(
      "not_object",
      "The block must be ONE JSON object \u2014 not an array, a string, or several objects."
    );
    return { issues: is.list };
  }
  const type = data.type;
  if (typeof type !== "string") {
    is.error("missing_type", "`type` is required: one of choice, form, steps, callout.", "type");
    return { issues: is.list };
  }
  let spec;
  switch (type) {
    case "choice":
      spec = parseChoice(is, data);
      break;
    case "form":
      spec = parseForm(is, data);
      break;
    case "steps":
      spec = parseSteps(is, data);
      break;
    case "callout":
      spec = parseCallout(is, data);
      break;
    default:
      is.error(
        "unknown_type",
        `Unknown type "${type}"; the catalog has choice, form, steps and callout.`,
        "type"
      );
      return { issues: is.list, type };
  }
  const result = { issues: is.list, type };
  if (spec !== void 0 && !is.hasError) result.spec = spec;
  return result;
}

// packages/core/src/a2ui/fences.ts
function splitLines(markdown) {
  return markdown.split("\n").map((line) => line.endsWith("\r") ? line.slice(0, -1) : line);
}
var OPEN_FENCE = /^( {0,3})(`{3,}|~{3,})(.*)$/;
var CLOSE_FENCE = /^ {0,3}(`{3,}|~{3,})\s*$/;
function scanFences(markdown) {
  const lines = splitLines(markdown);
  const spans = [];
  let open = null;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (open === null) {
      const m = OPEN_FENCE.exec(line);
      if (!m) continue;
      const run2 = m[2] ?? "";
      const info = (m[3] ?? "").trim();
      const char = run2.startsWith("~") ? "~" : "`";
      if (char === "`" && info.includes("`")) continue;
      open = {
        char,
        length: run2.length,
        indent: (m[1] ?? "").length,
        info,
        lang: (info.split(/\s+/)[0] ?? "").toLowerCase(),
        startLine: i + 1,
        endLine: i + 1,
        closed: false,
        body: []
      };
      continue;
    }
    const close = CLOSE_FENCE.exec(line);
    const run = close?.[1] ?? "";
    if (close && run.startsWith(open.char) && run.length >= open.length) {
      open.endLine = i + 1;
      open.closed = true;
      spans.push(open);
      open = null;
      continue;
    }
    open.body.push(stripIndent(line, open.indent));
  }
  if (open !== null) {
    open.endLine = lines.length;
    spans.push(open);
  }
  return spans;
}
function stripIndent(line, indent) {
  let n = 0;
  while (n < indent && line[n] === " ") n++;
  return line.slice(n);
}
function blocksFromFences(spans) {
  const blocks = [];
  for (const span of spans) {
    if (span.lang !== "a2ui" && span.lang !== "mermaid") continue;
    blocks.push({
      index: blocks.length + 1,
      fence: span.lang === "a2ui" ? "a2ui" : "mermaid",
      source: span.body.join("\n"),
      startLine: span.startLine,
      endLine: span.endLine,
      closed: span.closed,
      info: span.info
    });
  }
  return blocks;
}
function fenceLineSet(spans) {
  const set = /* @__PURE__ */ new Set();
  for (const span of spans) {
    for (let n = span.startLine; n <= span.endLine; n++) set.add(n);
  }
  return set;
}

// packages/core/src/a2ui/mermaid.ts
var MERMAID_TYPES = [
  "flowchart",
  "graph",
  "sequenceDiagram",
  "stateDiagram",
  "stateDiagram-v2",
  "classDiagram",
  "erDiagram",
  "gantt",
  "journey",
  "pie",
  "mindmap",
  "timeline",
  "gitGraph",
  "quadrantChart",
  "xychart-beta",
  "requirementDiagram",
  "C4Context"
];
var MERMAID_TYPE_SET = new Set(MERMAID_TYPES);
var BRACKET_CHECKED = /* @__PURE__ */ new Set([
  "flowchart",
  "graph",
  "stateDiagram",
  "stateDiagram-v2",
  "classDiagram",
  "erDiagram"
]);
var BRACES_PER_LINE = /* @__PURE__ */ new Set(["flowchart", "graph"]);
var BRACES_PER_DOCUMENT = /* @__PURE__ */ new Set([
  "classDiagram",
  "stateDiagram",
  "stateDiagram-v2"
]);
var FORBIDDEN = [
  { re: /^click\s/i, what: "a click binding" },
  { re: /^link\s+\S+\s+"/, what: "a link binding" },
  { re: /^callback\s/i, what: "a callback binding" },
  { re: /\bhref\s*[="]/i, what: "an href" },
  { re: /javascript:/i, what: "a javascript: URL" },
  { re: /<script/i, what: "a script tag" }
];
var NOT_A_STATEMENT = /^(end|subgraph\b|style\b|classDef\b|linkStyle\b|direction\b|title\b|dateFormat\b|axisFormat\b|section\b|x-axis\b|y-axis\b|accTitle\b|accDescr\b)/;
var issue = (level, code, message, line) => {
  const out = { level, code, message };
  if (line !== void 0) out.line = line;
  return out;
};
function unquoted(line) {
  let text = "";
  let inside = false;
  let quotes = 0;
  for (const ch of line) {
    if (ch === '"') {
      quotes++;
      inside = !inside;
      continue;
    }
    if (!inside) text += ch;
  }
  return { text, quotes };
}
var count = (text, ch) => text.split(ch).length - 1;
function checkLineBalance(line, n, braces, issues) {
  const { text, quotes } = unquoted(line);
  if (quotes % 2 === 1) {
    issues.push(
      issue(
        "error",
        "mermaid_unbalanced",
        `Line ${n} has an odd number of double quotes; close the quoted label.`,
        n
      )
    );
    return { text };
  }
  const pairs = [
    ["(", ")"],
    ["[", "]"]
  ];
  if (braces) pairs.push(["{", "}"]);
  for (const [open, close] of pairs) {
    const opens = count(text, open);
    const closes = count(text, close);
    if (opens === closes) continue;
    if (close === "]" && closes - opens === 1 && text.includes(">")) continue;
    issues.push(
      issue(
        "error",
        "mermaid_unbalanced",
        `Line ${n} has ${opens} "${open}" and ${closes} "${close}"; a label with brackets must be quoted, e.g. A["text (detail)"].`,
        n
      )
    );
  }
  return { text };
}
function checkMermaid(source) {
  const issues = [];
  const lines = splitLines(source);
  const firstIdx = lines.findIndex((line) => line.trim() !== "");
  if (firstIdx === -1) {
    issues.push(issue("error", "mermaid_empty", "The mermaid fence is empty; write a diagram."));
    return issues;
  }
  let start = 0;
  if ((lines[firstIdx] ?? "").trim() === "---") {
    const close = lines.findIndex((line, i) => i > firstIdx && line.trim() === "---");
    if (close === -1) {
      issues.push(
        issue(
          "error",
          "mermaid_unbalanced",
          "The frontmatter opened with --- is never closed; add the closing --- or drop it.",
          firstIdx + 1
        )
      );
      return issues;
    }
    for (let i = firstIdx + 1; i < close; i++) {
      const m = /^\s*([A-Za-z_][\w-]*)\s*:/.exec(lines[i] ?? "");
      if (m && m[1] !== "title") {
        issues.push(
          issue(
            "error",
            "mermaid_directive",
            `Frontmatter key \`${m[1]}\` is not allowed (only \`title\`); the app configures the diagram, not the model.`,
            i + 1
          )
        );
      }
    }
    start = close + 1;
  }
  let header;
  let statements = 0;
  let braceBalance = 0;
  for (let i = start; i < lines.length; i++) {
    const n = i + 1;
    const line = (lines[i] ?? "").trim();
    if (line === "") continue;
    if (line.includes("%%{")) {
      issues.push(
        issue(
          "error",
          "mermaid_directive",
          `Line ${n} carries an init directive (%%{ \u2026 }%%); remove it \u2014 the app sets the theme.`,
          n
        )
      );
      continue;
    }
    if (line.startsWith("%%")) continue;
    if (header === void 0) {
      header = /^([A-Za-z][\w-]*)/.exec(line)?.[1] ?? line;
      if (!MERMAID_TYPE_SET.has(header)) {
        issues.push(
          issue(
            "error",
            "mermaid_unknown_type",
            `"${header}" is not a supported diagram; start with one of ${MERMAID_TYPES.join(", ")}.`,
            n
          )
        );
      }
      continue;
    }
    for (const rule of FORBIDDEN) {
      if (rule.re.test(line)) {
        issues.push(
          issue(
            "error",
            "mermaid_forbidden",
            `Line ${n} carries ${rule.what}; links, clicks and scripts are not rendered \u2014 describe the target in the prose instead.`,
            n
          )
        );
        break;
      }
    }
    if (!NOT_A_STATEMENT.test(line)) statements++;
    if (BRACKET_CHECKED.has(header)) {
      const { text } = checkLineBalance(line, n, BRACES_PER_LINE.has(header), issues);
      if (BRACES_PER_DOCUMENT.has(header)) braceBalance += count(text, "{") - count(text, "}");
    }
  }
  if (header === void 0) {
    issues.push(
      issue("error", "mermaid_empty", "The mermaid fence has no diagram header; write one.")
    );
    return issues;
  }
  if (braceBalance !== 0) {
    issues.push(
      issue(
        "error",
        "mermaid_unbalanced",
        `The diagram opens ${braceBalance > 0 ? braceBalance + " more { than }" : -braceBalance + " more } than {"}; close every block.`,
        lines.length
      )
    );
  }
  if (statements > A2UI_LIMITS.mermaid.statements || lines.length > A2UI_LIMITS.mermaid.lines) {
    issues.push(
      issue(
        "warning",
        "mermaid_too_big",
        `The diagram has ${statements} statements over ${lines.length} lines; more than ${A2UI_LIMITS.mermaid.statements} nodes or edges is hard to read \u2014 split it or show only the main path.`
      )
    );
  }
  return issues;
}

// packages/core/src/a2ui/prose.ts
var PROSE_LIMITS = {
  enSentenceWords: 25,
  zhSentenceChars: 60,
  paragraphSentences: 5,
  /** A paragraph this long with no sentence break the splitter could find. */
  wallChars: 800,
  listDepth: 2
};
var A2UI_VAGUE_WORDS = {
  en: ["etc.", "and so on", "various", "appropriate", "appropriately", "stuff", "things"],
  zh: ["\u7B49\u7B49", "\u4E4B\u7C7B", "\u76F8\u5173\u7684", "\u8FDB\u884C", "\u67D0\u79CD\u7A0B\u5EA6\u4E0A"]
};
var CJK = new RegExp("\\p{Script=Han}|\\p{Script=Hiragana}|\\p{Script=Katakana}|\\p{Script=Hangul}", "gu");
var LATIN = new RegExp("\\p{Script=Latin}", "gu");
var WORD = /[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*/gu;
function cleanInline(text) {
  return text.replace(/`+[^`]*`+/g, " ").replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1").replace(/\[([^\]]*)\]\([^)]*\)/g, "$1").replace(/<https?:\/\/[^>]*>/g, " ").replace(/https?:\/\/\S+/g, " ").replace(/<\/?[A-Za-z][^>]*>/g, " ").replace(/[*~]+/g, "").replace(/\b_+|_+\b/g, "").replace(/\s+/g, " ").trim();
}
var HEADING = /^\s{0,3}#{1,6}(\s|$)/;
var TABLE_ROW = /^\s*\|/;
var THEMATIC_BREAK = /^\s{0,3}([-*_])(\s*\1){2,}\s*$/;
var LIST_ITEM = /^(\s*)(?:[-*+]|\d{1,3}[.)])\s+(.*)$/;
var LIST_MARKER = /^(\s*)(?:[-*+]|\d{1,3}[.)])\s+/;
var QUOTE = /^\s{0,3}>\s?(.*)$/;
function proseParagraphs(markdown) {
  const lines = splitLines(markdown);
  const fenced = fenceLineSet(scanFences(markdown));
  const paragraphs = [];
  let current = null;
  let inComment = false;
  const flush = () => {
    if (current !== null && current.text.trim() !== "") paragraphs.push(current);
    current = null;
  };
  const append = (p, text, line) => {
    if (text === "") return;
    if (p.text !== "") p.text += " ";
    p.offsets.push({ offset: p.text.length, line });
    p.text += text;
  };
  for (let i = 0; i < lines.length; i++) {
    const n = i + 1;
    if (fenced.has(n)) {
      flush();
      continue;
    }
    let line = lines[i] ?? "";
    if (inComment) {
      const end = line.indexOf("-->");
      if (end === -1) continue;
      line = line.slice(end + 3);
      inComment = false;
    }
    line = line.replace(/<!--[\s\S]*?-->/g, "");
    const open = line.indexOf("<!--");
    if (open !== -1) {
      line = line.slice(0, open);
      inComment = true;
    }
    if (line.trim() === "" || HEADING.test(line) || TABLE_ROW.test(line) || THEMATIC_BREAK.test(line)) {
      flush();
      continue;
    }
    const item = LIST_ITEM.exec(line);
    if (item) {
      flush();
      current = { text: "", startLine: n, kind: "item", offsets: [] };
      append(current, cleanInline(item[2] ?? ""), n);
      continue;
    }
    const quote = QUOTE.exec(line);
    if (quote) {
      if (current === null || current.kind !== "quote") {
        flush();
        current = { text: "", startLine: n, kind: "quote", offsets: [] };
      }
      append(current, cleanInline(quote[1] ?? ""), n);
      continue;
    }
    if (current === null) current = { text: "", startLine: n, kind: "para", offsets: [] };
    append(current, cleanInline(line.trim()), n);
  }
  flush();
  return paragraphs;
}
function detectLang(markdown) {
  const text = proseParagraphs(markdown).map((p) => p.text).join(" ");
  const cjk = text.match(CJK)?.length ?? 0;
  const latin = text.match(LATIN)?.length ?? 0;
  return cjk > 0 && cjk * 2 >= latin ? "zh" : "en";
}
function resolveLang(markdown, lang) {
  return lang !== void 0 && lang !== "auto" ? lang : detectLang(markdown);
}
var EN_BOUNDARY = /[.!?…]+["'”’)\]]*(?=\s+(?:[A-Z0-9"“'(\[]|$)|\s*$)|[。！？]+/g;
var ZH_BOUNDARY = /[。！？；]+|[.!?]+(?=\s|$)/g;
function splitSentences(text, lang) {
  const re = new RegExp((lang === "zh" ? ZH_BOUNDARY : EN_BOUNDARY).source, "g");
  const raw = [];
  let last = 0;
  for (let m = re.exec(text); m !== null; m = re.exec(text)) {
    if (m[0].length === 0) {
      re.lastIndex++;
      continue;
    }
    const end = m.index + m[0].length;
    raw.push({ text: text.slice(last, end), offset: last });
    last = end;
  }
  if (last < text.length) raw.push({ text: text.slice(last), offset: last });
  return raw.map((s) => {
    const lead = s.text.length - s.text.trimStart().length;
    return { text: s.text.trim(), offset: s.offset + lead };
  }).filter((s) => /[\p{L}\p{N}]/u.test(s.text));
}
var countWords = (text) => (text.match(WORD) ?? []).length;
var countChars = (text) => [...text.replace(/\s+/g, "")].length;
var IRREGULAR_PARTICIPLES = "built|done|made|given|taken|written|seen|known|shown|sent|chosen|found|held|kept|left|lost|put|read|run|set|sold|told|thought|understood|cut|hit|met|paid|said|spent|won|caught|taught|brought|bought|begun|broken|driven|eaten|forgotten|frozen|hidden|spoken|stolen|drawn|grown|thrown|torn|led|fed|lit|split|spread|shut|forbidden|withdrawn|overridden|undone|rebuilt|rewritten|proven|beaten|bitten|woven|shaken|woken|sworn|bound|wound|struck|stuck|swung|hung|sung|flung|spun|bent|lent|meant|dealt|felt|learnt";
var PASSIVE_SOURCE = `\\b(?:am|is|are|was|were|be|been|being|get|gets|got|getting)\\s+(?:(?:not|always|often|usually|also|already|still|never|then|now|only|just|automatically|first|later|rarely|sometimes|typically|currently|normally|partially|fully|easily)\\s+)?(\\w{2,}ed|${IRREGULAR_PARTICIPLES})\\b`;
var NOT_PARTICIPLES = /* @__PURE__ */ new Set([
  "indeed",
  "need",
  "speed",
  "seed",
  "feed",
  "bleed",
  "breed",
  "deed",
  "reed",
  "weed",
  "greed",
  "proceed",
  "exceed",
  "succeed",
  "hundred",
  "naked",
  "wicked",
  "rugged",
  "sacred",
  "shed",
  "fled",
  "tired",
  "interested",
  "excited",
  "worried",
  "bored",
  "pleased",
  "surprised",
  "satisfied",
  "disappointed",
  "scared",
  "confused",
  "embarrassed",
  "relaxed",
  "annoyed",
  "amazed",
  "delighted",
  "frustrated"
]);
function passiveIn(sentence) {
  const re = new RegExp(PASSIVE_SOURCE, "gi");
  for (let m = re.exec(sentence); m !== null; m = re.exec(sentence)) {
    if (!NOT_PARTICIPLES.has((m[1] ?? "").toLowerCase())) return m[0];
  }
  return void 0;
}
var EN_VAGUE = A2UI_VAGUE_WORDS.en.map((word) => ({
  word,
  re: new RegExp(
    `\\b${word.replace(/\./g, "").replace(/ /g, "\\s+")}${word.endsWith(".") ? "\\b\\.?" : "(?!\\p{L})"}`,
    "iu"
  )
}));
function excerpt(text) {
  const chars = [...text];
  return chars.length > 60 ? chars.slice(0, 60).join("") + "\u2026" : text;
}
function lineAt(p, offset) {
  let line = p.startLine;
  for (const entry2 of p.offsets) {
    if (entry2.offset <= offset) line = entry2.line;
    else break;
  }
  return line;
}
var warn = (code, message, line) => ({
  level: "warning",
  code,
  message,
  line
});
function lintListDepth(markdown, issues) {
  const lines = splitLines(markdown);
  const fenced = fenceLineSet(scanFences(markdown));
  const stack = [];
  let flagged = false;
  const top = () => stack[stack.length - 1] ?? -1;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (fenced.has(i + 1)) continue;
    if (line.trim() === "") continue;
    const m = LIST_MARKER.exec(line);
    if (!m) {
      if (/^\S/.test(line)) {
        stack.length = 0;
        flagged = false;
      }
      continue;
    }
    const indent = (m[1] ?? "").replace(/\t/g, "    ").length;
    while (stack.length > 0 && indent < top()) stack.pop();
    if (stack.length === 0 || indent > top()) stack.push(indent);
    if (stack.length > PROSE_LIMITS.listDepth && !flagged) {
      flagged = true;
      issues.push(
        warn(
          "deep_nesting",
          `A list nested ${stack.length} levels deep (line ${i + 1}); keep lists to ${PROSE_LIMITS.listDepth} levels, or split them into sections.`,
          i + 1
        )
      );
    }
  }
}
function lintProse(markdown, opts = {}) {
  const lang = resolveLang(markdown, opts.lang);
  const issues = [];
  for (const p of proseParagraphs(markdown)) {
    const sentences = splitSentences(p.text, lang);
    const chars = countChars(p.text);
    if (p.kind === "para" && chars > PROSE_LIMITS.wallChars) {
      issues.push(
        warn(
          "wall_of_text",
          `A paragraph of ${chars} characters with no sentence break the reader can rest on; split it into short sentences and paragraphs.`,
          p.startLine
        )
      );
    } else if (p.kind === "para" && sentences.length > PROSE_LIMITS.paragraphSentences) {
      issues.push(
        warn(
          "long_paragraph",
          `A paragraph of ${sentences.length} sentences (limit ${PROSE_LIMITS.paragraphSentences}); split it, or turn the items into a list.`,
          p.startLine
        )
      );
    }
    for (const s of sentences) {
      const line = lineAt(p, s.offset);
      if (lang === "en") {
        const words = countWords(s.text);
        if (words > PROSE_LIMITS.enSentenceWords) {
          issues.push(
            warn(
              "long_sentence",
              `A sentence of ${words} words (limit ${PROSE_LIMITS.enSentenceWords}): "${excerpt(s.text)}". Split it: one idea per sentence.`,
              line
            )
          );
        }
        const passive = passiveIn(s.text);
        if (passive !== void 0) {
          issues.push(
            warn(
              "passive_voice",
              `Passive voice ("${passive}") in: "${excerpt(s.text)}". Say who does it \u2014 use the active voice, or the imperative for an instruction.`,
              line
            )
          );
        }
        for (const { word, re } of EN_VAGUE) {
          if (re.test(s.text)) {
            issues.push(
              warn(
                "vague_word",
                `Vague word "${word}" in: "${excerpt(s.text)}". Name the items or the exact action instead.`,
                line
              )
            );
          }
        }
      } else {
        const n = countChars(s.text);
        if (n > PROSE_LIMITS.zhSentenceChars) {
          issues.push(
            warn(
              "long_sentence",
              `A sentence of ${n} characters (limit ${PROSE_LIMITS.zhSentenceChars}): "${excerpt(s.text)}". Split it at the commas into full sentences.`,
              line
            )
          );
        }
        for (const word of A2UI_VAGUE_WORDS.zh) {
          if (s.text.includes(word)) {
            issues.push(
              warn(
                "vague_word",
                `Vague word "${word}" in: "${excerpt(s.text)}". Name the items or the exact action instead (\u300C\u8FDB\u884C\u5B89\u88C5\u300D\u2192\u300C\u5B89\u88C5\u300D).`,
                line
              )
            );
          }
        }
      }
    }
  }
  lintListDepth(markdown, issues);
  return issues;
}

// packages/core/src/a2ui/check.ts
var HEADING2 = /^\s{0,3}#{1,6}(\s|$)/;
var TABLE_ROW2 = /^\s*\|/;
var THEMATIC_BREAK2 = /^\s{0,3}([-*_])(\s*\1){2,}\s*$/;
function checkReply(markdown, opts = {}) {
  const lang = resolveLang(markdown, opts.lang);
  const lines = splitLines(markdown);
  const spans = scanFences(markdown);
  const blocks = blocksFromFences(spans);
  const fenced = fenceLineSet(spans);
  const issues = [];
  const summary = [];
  const typeOf = /* @__PURE__ */ new Map();
  for (const block of blocks) {
    const own = [];
    let type;
    if (!block.closed) {
      own.push({
        level: "error",
        code: "unclosed_fence",
        message: `The ${block.fence} fence opened on line ${block.startLine} is never closed; add the closing fence line.`,
        line: block.startLine
      });
    }
    let relative;
    if (block.fence === "a2ui") {
      const result = parseA2ui(block.source);
      type = result.spec?.type ?? result.type;
      relative = result.issues;
    } else {
      relative = checkMermaid(block.source);
    }
    for (const issue2 of relative) {
      own.push(issue2.line !== void 0 ? { ...issue2, line: block.startLine + issue2.line } : issue2);
    }
    for (const issue2 of own) {
      issues.push({ ...issue2, block: block.index, scope: issue2.level === "error" ? "l1" : "l2" });
    }
    const entry2 = {
      index: block.index,
      fence: block.fence,
      ok: own.every((issue2) => issue2.level !== "error")
    };
    if (type !== void 0) entry2.type = type;
    summary.push(entry2);
    typeOf.set(block.index, type);
  }
  const l2 = (code, message, block, line) => {
    const issue2 = { level: "warning", code, message, scope: "l2" };
    if (block !== void 0) issue2.block = block;
    if (line !== void 0) issue2.line = line;
    issues.push(issue2);
  };
  const label = (index, fence) => fence === "mermaid" ? "mermaid" : typeOf.get(index) ?? "a2ui";
  const interactive = blocks.filter((b) => {
    const t = typeOf.get(b.index);
    return b.fence === "a2ui" && (t === "choice" || t === "form");
  });
  if (interactive.length > 2 || blocks.length > 4) {
    l2(
      "ui_overuse",
      `${blocks.length} blocks (${interactive.length} interactive) in one reply; keep to one or two blocks and at most two questions, or answer in prose.`
    );
  }
  for (const b of interactive) {
    if (lines.slice(b.endLine).some((line) => line.trim() !== "")) {
      l2(
        "interactive_not_last",
        `Content follows the ${label(b.index, b.fence)} block that ends on line ${b.endLine}; a question ends the turn \u2014 move the block to the end, or drop what follows.`,
        b.index,
        b.endLine
      );
    }
  }
  for (const b of blocks) {
    let i = b.startLine - 2;
    while (i >= 0 && (lines[i] ?? "").trim() === "") i--;
    const above = i >= 0 ? lines[i] ?? "" : "";
    const grounded = i >= 0 && !fenced.has(i + 1) && !HEADING2.test(above) && !TABLE_ROW2.test(above) && !THEMATIC_BREAK2.test(above) && !above.trimStart().startsWith("<!--");
    if (!grounded) {
      l2(
        "ungrounded_block",
        `The ${label(b.index, b.fence)} block on line ${b.startLine} is not introduced; write one sentence before it that says what it is for.`,
        b.index,
        b.startLine
      );
    }
  }
  for (const issue2 of lintProse(markdown, { lang })) issues.push({ ...issue2, scope: "prose" });
  const errors = issues.filter((issue2) => issue2.level === "error").length;
  const l2Warnings = issues.filter(
    (issue2) => issue2.level === "warning" && issue2.scope === "l2"
  ).length;
  const proseWarnings = issues.filter((issue2) => issue2.scope === "prose").length;
  const l1Score = errors === 0 ? 100 : 0;
  const l2Score = Math.max(0, 100 - A2UI_SCORING.l2PerWarning * l2Warnings);
  const proseScore = Math.max(0, 100 - A2UI_SCORING.prosePerWarning * proseWarnings);
  const total = errors > 0 ? 0 : Math.round(A2UI_SCORING.l2Weight * l2Score + A2UI_SCORING.proseWeight * proseScore);
  return {
    ok: errors === 0,
    blocks: summary,
    issues,
    score: { l1: l1Score, l2: l2Score, prose: proseScore, total },
    lang
  };
}

// packages/core/src/a2ui/rubric.ts
var A2UI_RUBRIC = {
  en: [
    "Would plain text have served the reader as well? If yes, remove the block.",
    "Does a sentence before each block say what it is for, so no block arrives unexplained?",
    "Is each component the right one: choice for one decision, form for several answers at once, steps for a procedure, callout for one warning or tip, mermaid for a structure or a flow?",
    "Do the options cover the realistic answers, with one marked recommended when you have a view, and is the question the last thing in the reply?",
    "Is the reply what a person would naturally say: short sentences, one instruction each, no filler?",
    "Can the reader take everything in at a glance: at most 5 options, 4 fields, 10 steps, one or two blocks?",
    "Did you keep UI out of a plain fact, a conversational turn or an emotional moment?"
  ],
  zh: [
    "\u6362\u6210\u7EAF\u6587\u672C\u662F\u5426\u540C\u6837\u6E05\u695A\uFF1F\u5982\u679C\u662F\uFF0C\u5220\u6389\u8FD9\u4E2A\u7EC4\u4EF6\u3002",
    "\u6BCF\u4E2A\u7EC4\u4EF6\u524D\u9762\u662F\u5426\u6709\u4E00\u53E5\u8BDD\u8BF4\u660E\u5B83\u662F\u5E72\u4EC0\u4E48\u7684\uFF0C\u6CA1\u6709\u7EC4\u4EF6\u662F\u7A81\u7136\u51FA\u73B0\u7684\uFF1F",
    "\u7EC4\u4EF6\u9009\u5BF9\u4E86\u5417\uFF1Achoice \u7528\u4E8E\u4E00\u4E2A\u51B3\u5B9A\uFF0Cform \u7528\u4E8E\u4E00\u6B21\u56DE\u7B54\u591A\u4E2A\u95EE\u9898\uFF0Csteps \u7528\u4E8E\u64CD\u4F5C\u6B65\u9AA4\uFF0Ccallout \u7528\u4E8E\u4E00\u6761\u8B66\u544A\u6216\u63D0\u793A\uFF0Cmermaid \u7528\u4E8E\u7ED3\u6784\u6216\u6D41\u7A0B\uFF1F",
    "\u9009\u9879\u662F\u5426\u8986\u76D6\u4E86\u73B0\u5B9E\u4E2D\u7684\u7B54\u6848\uFF0C\u6709\u503E\u5411\u65F6\u662F\u5426\u6807\u4E86\u4E00\u4E2A\u63A8\u8350\u9879\uFF0C\u95EE\u9898\u662F\u5426\u653E\u5728\u56DE\u590D\u7684\u6700\u540E\uFF1F",
    "\u8FD9\u6BB5\u56DE\u590D\u50CF\u4E0D\u50CF\u4E00\u4E2A\u4EBA\u81EA\u7136\u4F1A\u8BF4\u7684\u8BDD\uFF1A\u77ED\u53E5\u3001\u4E00\u53E5\u4E00\u4E2A\u6307\u4EE4\u3001\u6CA1\u6709\u5E9F\u8BDD\uFF1F",
    "\u8BFB\u8005\u80FD\u5426\u4E00\u773C\u770B\u5B8C\uFF1A\u9009\u9879\u4E0D\u8D85\u8FC7 5 \u4E2A\u3001\u5B57\u6BB5\u4E0D\u8D85\u8FC7 4 \u4E2A\u3001\u6B65\u9AA4\u4E0D\u8D85\u8FC7 10 \u6B65\u3001\u7EC4\u4EF6\u4E0D\u8D85\u8FC7\u4E00\u4E24\u4E2A\uFF1F",
    "\u5BF9\u4E8E\u4E00\u53E5\u8BDD\u7684\u4E8B\u5B9E\u3001\u95F2\u804A\u6216\u60C5\u7EEA\u6027\u7684\u5BF9\u8BDD\uFF0C\u662F\u5426\u6CA1\u6709\u4F7F\u7528\u7EC4\u4EF6\uFF1F"
  ]
};

// packages/core/src/a2ui/report.ts
var plural = (n, word) => `${n} ${word}${n === 1 ? "" : "s"}`;
function where(issue2) {
  const parts = [];
  if (issue2.block !== void 0) parts.push(`block ${issue2.block}`);
  if (issue2.line !== void 0) parts.push(`line ${issue2.line}`);
  if (issue2.path !== void 0) parts.push(issue2.path);
  return parts.length > 0 ? `[${parts.join(" ")}] ` : "";
}
function formatReport(report, opts = {}) {
  const errors = report.issues.filter((issue2) => issue2.level === "error");
  const l2 = report.issues.filter((issue2) => issue2.level === "warning" && issue2.scope !== "prose");
  const prose = report.issues.filter((issue2) => issue2.scope === "prose");
  const out = [
    `a2ui check: ${plural(report.blocks.length, "block")}, ${plural(errors.length, "error")}, ${plural(l2.length + prose.length, "warning")} (lang ${report.lang})`
  ];
  for (const block of report.blocks) {
    out.push(
      `  block ${block.index}: ${block.fence}${block.type !== void 0 ? ` ${block.type}` : ""} \u2014 ${block.ok ? "ok" : "ERROR"}`
    );
  }
  if (report.blocks.length === 0) out.push("  no a2ui or mermaid blocks; prose rules only");
  const section = (title, list) => {
    if (list.length === 0) return;
    out.push("", title);
    for (const issue2 of list) out.push(`  ${where(issue2)}${issue2.code}: ${issue2.message}`);
  };
  section("errors (fix before sending):", errors);
  section("warnings \u2014 blocks (L2):", l2);
  section("warnings \u2014 prose (STE):", prose);
  const s = report.score;
  const verdict = errors.length > 0 ? "total is 0 while any error remains" : s.total < A2UI_SCORING.passTotal ? `below the ${A2UI_SCORING.passTotal} gate; fix the warnings that matter` : "pass";
  out.push("", `score: L1 ${s.l1}  L2 ${s.l2}  prose ${s.prose}  total ${s.total}  (${verdict})`);
  if (opts.rubric) {
    out.push("", "self-review before sending:");
    A2UI_RUBRIC[report.lang].forEach((question, i) => out.push(`  ${i + 1}. ${question}`));
  }
  return out.join("\n");
}

// packages/core/src/a2ui/cli.ts
var USAGE = `usage: node check.mjs [draft.md] [--lang zh|en|auto] [--json] [--rubric]

Checks a reply that carries a2ui or mermaid blocks: L1 validity per block, L2 heuristics across
blocks, the STE-lite prose lint, and a score. Reads the file, or stdin when no file is given.
  --lang      prose rules and rubric language; auto (default) picks zh when CJK dominates
  --json      print the report as JSON instead of text
  --rubric    append the self-review questions
exit code: 0 no errors \xB7 1 at least one error \xB7 2 usage or I/O failure`;
var LANGS = /* @__PURE__ */ new Set(["zh", "en", "auto"]);
function runCli(argv, io) {
  let file;
  let lang = "auto";
  let json = false;
  let rubric = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i] ?? "";
    if (arg === "--help" || arg === "-h") {
      io.out(USAGE);
      return 0;
    }
    if (arg === "--json") {
      json = true;
    } else if (arg === "--rubric") {
      rubric = true;
    } else if (arg === "--lang" || arg.startsWith("--lang=")) {
      const value = arg === "--lang" ? argv[++i] ?? "" : arg.slice("--lang=".length);
      if (!LANGS.has(value)) {
        io.err(`--lang must be zh, en or auto (got "${value}")
${USAGE}`);
        return 2;
      }
      lang = value;
    } else if (arg.startsWith("-") && arg !== "-") {
      io.err(`unknown option ${arg}
${USAGE}`);
      return 2;
    } else if (file === void 0) {
      file = arg;
    } else {
      io.err(`only one file can be checked at a time
${USAGE}`);
      return 2;
    }
  }
  let markdown;
  try {
    if (file === void 0 || file === "-") {
      if (io.stdinIsTTY) {
        io.err(USAGE);
        return 2;
      }
      markdown = io.readStdin();
    } else {
      markdown = io.readFile(file);
    }
  } catch (err) {
    io.err(`cannot read ${file ?? "stdin"}: ${err instanceof Error ? err.message : String(err)}`);
    return 2;
  }
  const report = checkReply(markdown, { lang });
  io.out(json ? JSON.stringify(report, null, 2) : formatReport(report, { rubric }));
  return report.ok ? 0 : 1;
}
var entry = process.argv[1] !== void 0 ? path.resolve(process.argv[1]) : "";
if (entry !== "" && entry === fileURLToPath(import.meta.url)) {
  process.exitCode = runCli(process.argv.slice(2), {
    readStdin: () => readFileSync(0, "utf8"),
    stdinIsTTY: process.stdin.isTTY === true,
    readFile: (file) => readFileSync(file, "utf8"),
    out: (text) => console.log(text),
    err: (text) => console.error(text)
  });
}
export {
  USAGE,
  runCli
};
